### ISSUE TITLE
Ads in full screen plays in background but doesn't show on iOS

### ISSUE THREAD

**Issue by sdahdaah** [googleads/videojs-ima#627] opened 2018-05-27 20:59 UTC
Hello,

After upgrading to the latest controb-ads and latest ima ads on iOS iPhone plays in background when in full screen.

**Comment by sdahdaah** [comment] 2018-05-27 22:26
using IMA 1.3.0 works with no issue even with latest contrib-ads the problem is with IMA 1.4.0 where ads on iPhone plays in background while in full screen and plays with no issue when playback is inline only

**Comment by ypavlotsky** [comment] 2018-05-29 17:41
Hi, I was able to reproduce your issue, and we've reached out to the IMA SDK team to see if this is a bug on their end. I'll keep you updated here.

**Comment by sdahdaah** [comment] 2018-06-07 19:04
any news about a fix for that?

**Comment by ypavlotsky** [comment] 2018-06-08 19:52
So I think that #638 actually fixes this issue, and should cause everything to be inline as long as `disableCustomPlaybackOnIOS10Plus` is set and `playsinline` is set on the video tag.

**Comment by shawnbuso** [comment] 2018-06-11 15:20
According to @sdahdaah this is still not fixed. From #638:

"""
After upgrading to the latest controb-ads and latest ima ads on iOS iPhone plays in background when in full screen. using IMA 1.3.0 works with no issue even with latest contrib-ads the problem is with IMA 1.4.0 where ads on iPhone plays in background while in full screen and plays with no issue when playback is inline only.

So create a player with IMA 1.4.0 open the link from an iPhone NOT IPAD, click full screen as soon as the ad starts you will hear it but not see it as it is running in background.
"""

**Comment by sdahdaah** [comment] 2018-06-12 00:54
UPDATE:

after upgrading to 1.5.1 issue is solved. However after postroll i get the below on iOS Safari, it just appears after post-roll.

IMA 1.5.1
Contrib-ads: 6.4.1
Player: 6.7.3

VIDEOJS: – "ERROR:" – "(CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED)" – "No compatible source was found for this media."
st

code: 4

message: "No compatible source was found for this media."

st Prototype

MEDIA_ERR_ABORTED: 1

MEDIA_ERR_CUSTOM: 0

MEDIA_ERR_DECODE: 3

MEDIA_ERR_ENCRYPTED: 5

MEDIA_ERR_NETWORK: 2

MEDIA_ERR_SRC_NOT_SUPPORTED: 4

code: 0

constructor: function(t)

MEDIA_ERR_ABORTED: 1

MEDIA_ERR_CUSTOM: 0

MEDIA_ERR_DECODE: 3

MEDIA_ERR_ENCRYPTED: 5

MEDIA_ERR_NETWORK: 2

MEDIA_ERR_SRC_NOT_SUPPORTED: 4

arguments: null

caller: null

defaultMessages: {1: "You aborted the media playback", 2: "A network error caused the media download to fail part-way.", 3: "The media playback was aborted due to a corruption…media used features your browser did not support.", 4: "The media could not be loaded, either because the …rk failed or because the format is not supported.", 5: "The media is encrypted and we do not have the keys to decrypt it."}

errorTypes: ["MEDIA_ERR_CUSTOM", "MEDIA_ERR_ABORTED", "MEDIA_ERR_NETWORK", "MEDIA_ERR_DECODE", "MEDIA_ERR_SRC_NOT_SUPPORTED", "MEDIA_ERR_ENCRYPTED"] (6)

length: 1

name: "st"

prototype: st {code: 0, message: "", status: null, MEDIA_ERR_CUSTOM: 0, MEDIA_ERR_ABORTED: 1, …}

Function Prototype

message: ""

status: null

Object Prototype
Je — video.min.js:1377
error — video.min.js:1410
error — video.min.js:5764:243
(anonymous function) — video.min.js:5713
r — video.min.js:1527


Regards,

**Comment by ypavlotsky** [comment] 2018-06-12 14:33
Could you open that post-roll issue as it's own separate issue? Thanks!

**Comment by sdahdaah** [comment] 2018-06-12 14:37
sure done.

**Comment by ypavlotsky** [comment] 2018-06-12 14:55
Closing this issue out as it appears to have been resolved in 1.5.1.

**Comment by sdahdaah** [comment] 2019-12-21 00:24
Same bug again with IMA 1.7.4 and iOS 13.3 ads play in the background

**Comment by Kiro705** [comment] 2020-01-03 21:44
Hi @sdahdaah ,

Thanks for reaching out, is this issue reproducible using the [samples](https://googleads.github.io/videojs-ima/)?

Either way, could you please include steps to reproduce or a sample page to reproduce the issue?

**Closed** 2020-03-10 20:26 UTC
Labels: P2, bug
