### ISSUE TITLE
Content plays before ad

### ISSUE THREAD

**Issue by jamesgorrie** [googleads/videojs-ima#167] opened 2016-02-05 09:40 UTC
When content is played, we have a few milliseconds of the ad play first, before the content.

As much as this should be expected when the prerollTimout has been reached, [we already have our timeout set to 1000ms](https://github.com/guardian/frontend/blob/master/static/src/javascripts/bootstraps/enhanced/media/main.js#L254) (overkill, but I wanted to see if it fixed the problem).

[Content with this issue can be seen here](http://www.theguardian.com/commentisfree/video/2016/feb/03/social-mobility-is-cruel-heres-why-video).

I have dug into it and it seems a script pulled in by the `imasdk` pulls in a [Youtube script](https://s.ytimg.com/yts/jsbin/www-embed-player-vfliX6EpK/www-embed-player.js) that isn't ready for some time after page load. That's the only lead I have, although it might be a red herring.

**Comment by shawnbuso** [comment] 2016-02-05 15:11
Hi there,

Is your sample page still requesting ads? When I visit that I'm only seeing the content - no ads.

Also, did you flip "content" and "ads" in your first sentence? I think what you're trying to say is that you see a few milliseconds of content before your pre-roll, but it sounds like you might be saying the opposite.

Thanks,
Shawn

**Comment by jamesgorrie** [comment] 2016-02-05 17:03
Hello.

Indeed - I mean content -> ad -> content.

It doesn't seem so, you can however see when it becomes ready still.

Looking at the timeline the `ima3` script starts at about `960ms` (granted, slow). It then only completes, and the ads become available at about `3015ms`. I'm trying to find the bottleneck, any ideas?

**Comment by shawnbuso** [comment] 2016-02-05 18:21
I'm still not seeing any ads on your site, so I'm not able to replicate - I click play and I just get sent straight to content, no ads at all.

**Comment by jamesgorrie** [comment] 2016-02-08 10:56
Ah, I forgot to give you think link with the adtest turned on:
(Here it is](http://www.theguardian.com/commentisfree/video/2016/feb/03/social-mobility-is-cruel-heres-why-video?adtest=tom)...

**Comment by shawnbuso** [comment] 2016-02-08 16:08
Hmm I'm still not seeing an ad on that page, though I do get this error in the console:

VIDEOJS: ERROR: The "Vpaid" tech is undefined. Skipped browser support check for that tech.

**Comment by jamesgorrie** [comment] 2016-02-09 10:10
Do you have the `adtest=tom` querystring?
That uses a cookie to set the ad to play, so that might be a problem if you're blocking them.

The `Vpaid` error, we're aware of - it doesn't break anything else.

The error is definitely caused by the fact that the timeout is only respected after all the scripts are run that are included from this script itself. It seems like the running order is:
* Page loads, IMA script is loaded
* Content plays
* Scripts included by the `ima` script are downloaded and finish running
* Timeout kicks in, ads downloaded and played.

**Comment by shawnbuso** [comment] 2016-02-09 14:57
I do have the adtest=dom query string, and I'm not doing anything to block cookies. What timeout are you referring to when you say "the timeout is only respected after..."?

**Comment by aronallen** [comment] 2016-02-10 09:25
We are also experiencing a similar issue.
We briefly have playback on the first few frames of the content, before the preroll add kicks in.
We think it could be fixed by pre-warming IMA before playback is initialized.
In our current setup we have a boot strap service that loads the video.js bundle and the plugins we use after user interaction. If we were to pre-warm IMA we would need to be able to do so without video.js dependencies, since we don't want the most of the code loaded, if the user hasn't interacted.

**Comment by jamesgorrie** [comment] 2016-02-10 11:05
@aronallen - do you have an example to see if I can compare?

See my stats about how long it takes from ima load -> all the scripts stop running, hence I think it is the pre-warming.

**Comment by shawnbuso** [comment] 2016-03-28 14:39
Going to close as a duplicate of #178

**Comment by jamesgorrie** [comment] 2016-05-24 17:48
Asking to reopen due to [this example](https://jsfiddle.net/jamesgorrie/aofw550k/).
The duplicate bug mentions that it's the first frame - whereas this is a few frames.

**Comment by jamesgorrie** [comment] 2016-06-01 12:55
Updating example to not have all the other gumpf around it.
[See here](https://jsfiddle.net/jamesgorrie/qabbkxv5/).

**Comment by jamesgorrie** [comment] 2016-06-01 16:55
@shawnbuso would you prefer another issue?

**Comment by shawnbuso** [comment] 2016-06-01 17:17
Hey James,

Same issue is fine - I think it's the same problem in both cases, just that for some reason your video is playing through further before the ad starts.

Thanks,
Shawn

**Comment by ehoch** [comment] 2016-06-07 12:15
Just to confirm I'm still having this issue, particular with users with a slower Internet connection.  You can see the bug happening if you get a linear ad in these videos:

http://www.wellplated.com/oatmeal-breakfast-bars/
http://mykoreankitchen.com/spicy-cold-kimchi-noodles/

I'm going to increase my timeout to 5000ms like I read in the other referenced thread, but I wanted to note I'm seeing this bug as well.

**Comment by shawnbuso** [comment] 2016-06-09 15:02
Have you tried increasing the timeouts as suggested in #178? That's working for me in the other samples provided.

  prerollTimeout: 5000, timeout: 5000

**Comment by ehoch** [comment] 2016-06-09 15:08
I did and it seems to make the problem a lot less noticeable. However, some slower connections, particularly from a user in Australia, noted they're still seeing the content start for about a second before the ad kicks in.

**Comment by steevee** [comment] 2016-12-05 14:57
Those timeout contrib-ads options don't work for me. Even manually triggering `player.play()` causes a blip of content pre the preroll.

The length of the blip seems to vary depending on the length of the content video, ad video, and network speed.

The CSS hack to hide the video content visually works OK, but audio still plays. I've got a rather elaborate hack to solve for this:

```css
.vjs-ad-loading > video { opacity: 0 }
```

```js
player.on('adstart', function(imaAdStartEvent) {
    // 2. Because startFromReadyCallback() mirrors player volume, we need to override the muted ads volume on start
    imaAdStartEvent.getAdsManager().setVolume(1);
});

player.on('adend', function() {
    // 3. Re-enable volume, restart video from beginning
   player.setVolume(1);
   player.currentTime(0);
   player.play();
});

// 1. mute video before playing it
player.volume(0);
player.play();
```

This solution is clearly pretty awful! Some research I've been involved in suggests the blip is likely to irritate users, making them less receptive to the preroll ad, reducing creative performance, etc. Not ideal.

@shawnbuso do you think this issue lies with videojs-ima or videojs-contrib-ads?

**Comment by shawnbuso** [comment] 2016-12-05 20:36
I think the issue is a combo - the contrib-ads docs make it look like you must call play on the video player before you can play ads, so that's what we do. If it takes us a long time to get those ads then the content will start before we get ads playing. The contrib-ads plugin, however, does have some samples that show pre-rolls playing before calling play on the player, so if we can figure out how those work and refactor our plugin to behave the same way we might be able to fix this, though I think that will be a rather large refactor.

**Comment by Sivitas** [comment] 2017-04-01 00:17
Any progress or new thoughts on this issue? I'm using @steevee's hack which fixes the volume for me but the css doesn't seem to work for me. I've also set the prerollTime and timeout both to 5000 as well

**Comment by joshuairl** [comment] 2017-04-27 20:25
I'm also experiencing this issue too... any new tips?

**Comment by shawnbuso** [comment] 2017-07-20 15:13
Hi all,

We've been looking into this one and it looks like it will require a small re-write of the plugin to work with the latest contrib-ads plugin. That should make our current state machine much more simple and allow us to request and play ads without first playing the content video. This is no small task - right now we're hoping to get that work slated for Q4.

Thanks,
Shawn

**Comment by jonigl** [comment] 2017-11-30 20:52
Hi @shawnbuso, how are you?

Any update about this issue? 

I found that 14 days ago a new version was released (0.8.0) this version resolves this problem?

Thanks in advance. 

Greetings!

**Comment by shawnbuso** [comment] 2017-11-30 20:53
This one's not fixed by 0.8.0 but it will be fixed in 1.0.0, which will be coming before the end of the year. Stay tuned!

**Comment by jonigl** [comment] 2017-11-30 20:56
Awesome! Thanks! @shawnbuso

**Closed** 2017-12-12 17:38 UTC
Labels: bug

**Comment by jonigl** [comment] 2017-12-13 17:41
Hi  @shawnbuso I saw that the plugin was updated just few hours ago to v1.0.1 I'd like to know if this version is ready for production?

Thanks in advance!

**Comment by shawnbuso** [comment] 2017-12-13 19:22
You should be good to go with that new version, but it is a major version change so we recommend testing it before releasing. We changed the API a bit (you no longer have to call play() on the video player, you just need to initialize the plugin with options). I'd recommend taking a look at the updated sample for whichever sample most closely matches your implementation.

**Comment by canhnm** [comment] 2017-12-20 01:47
I also experienced the same problem.
Currently I do apply a hacky way on play event:
```
this.player.on('play', function(){
      var currentItem = _THIS.player.playlist.currentItem();
      var currentItemSource = _THIS.playlist;

        if('undefined'!==typeof _THIS.adTagUrl){
          setTimeout(function () {
            _THIS.player.pause();
          }, 200);
          _THIS.player.ima.initializeAdDisplayContainer();
          _THIS.player.ima.setContentWithAdTag(null, _THIS.adTagUrl, true);
          _THIS.player.ima.requestAds();
        }
});
```

**Comment by shawnbuso** [comment] 2017-12-20 14:55
@canhnm are you testing with >1.0.0? This should be resolved as of that release. Thanks!

**Comment by canhnm** [comment] 2017-12-22 02:59
@shawnbuso Sound great, I tested on 0.8.0
I am going to test with 1.0.1 soon. Thanks!

**Comment by shawnbuso** [comment] 2017-12-22 15:32
Sounds good, let me know how it works! Thanks!

**Comment by Klabauterman** [comment] 2022-01-19 10:15
I am still seeing this issue on version 1.11.0

**Comment by Klabauterman** [comment] 2022-01-19 10:25
It looks like the video only starts before the preroll when autoplay is enabled.

**Comment by Klabauterman** [comment] 2022-01-19 12:05
For any1 who is still facing this issue: Just don't use autoplay: true in the player options. Instead call play() when the player is ready.
