### ISSUE TITLE
Autoplay on Native Android browser

### ISSUE THREAD

**Issue by ibraalek10** [googleads/videojs-ima#543] opened 2018-03-01 16:55 UTC
Hi all,
can i ask you why the ads doesn't play successfully without a user interaction in Native Android browser?
In each mobile browser (iOs and Android) i haven't got any problem, the ads plays when video comes in viewport but with Native Android browser it is impossible.
Someone can help me?
Thanks too much

A.

**Comment by shawnbuso** [comment] 2018-03-01 18:07
If the video is playing sound this is a limitation of the platform - both [Android](https://developers.google.com/web/updates/2017/09/autoplay-policy-changes) and [iOS](https://webkit.org/blog/6784/new-video-policies-for-ios/) require a user interaction to start video with sound.

**Comment by ibraalek10** [comment] 2018-03-02 09:17
Hi @shawnbuso,
Thanks for the answer.
My tag <video> has the attributes "muted" and "playsinline", anyway i have this problem only with Native Android browser..

A.

**Comment by shawnbuso** [comment] 2018-03-02 16:32
Hmm in that case it should work - do you have a sample page where we can replicate? And by "Android Native Browser" do you mean Chrome on Android, or the browser that Android devices used before they started using Chrome?

**Comment by ibraalek10** [comment] 2018-03-02 17:39
Hi @shawnbuso,
this is a test page: http://4w-test-site.com/responsive/native.php.
The problem is on "Samsung Internet browser" (http://www.samsung.com/it/apps/samsung-internet/).

A.

**Comment by shawnbuso** [comment] 2018-03-02 21:40
Thanks for the info - I'll take a look at this and let you know if we can nail down what the issue is.

**Comment by shawnbuso** [comment] 2018-03-05 18:33
I took a look at this an unfortunately I don't think we'll be able to add support - the IMA SDK only officially supports Chrome on Android. Until the IMA SDK adds support I recommend using click-to-play for the Samsung browser.

**Comment by ibraalek10** [comment] 2018-03-06 09:10
Thanks @shawnbuso .
I think that is a problem of a ultimate release of the Samsung browser because until some time ago the ads started with a workaround (with the screen touch event).. Now, this workaround doesn't start!!!
Can i wait some info about this problem?
Thanks a lot

A.

**Comment by shawnbuso** [comment] 2018-03-06 15:22
No problem - I'll see if we can get a Samsung device on which we can debug this. Right now I don't have any recent Samsung devices so I'm not able to replicate.

**Comment by ibraalek10** [comment] 2018-03-06 15:27
Thanks a lot @shawnbuso .
I tested it with Samsung Galaxy S8.
I'll be waiting for your feedback.

A.

**Comment by shawnbuso** [comment] 2018-03-08 16:36
Will let you know once we are able to test. Thanks!

**Comment by ibraalek10** [comment] 2018-03-12 15:38
Hi @shawnbuso ,
With ultimate release of Android OS "Oreo" (Samsung browser 7.0.10.46), would seems that there isn't any problems.
I tested it with Samsung Galaxy S8 and the ads plays successfully with autoplay when the player comes in viewport.
Now, i don't know if there are problems with previous release of Android OS.
I'll be waiting every your feedback.
Thanks a lot,

A.

**Comment by shawnbuso** [comment] 2018-03-12 16:59
Thanks for the info - in that case it sounds like maybe this was a Samsung bug that they fixed with the newer Android release. If I can get my hands on an older, but not too old, Samsung device then we can try to investigate further.

**Comment by ibraalek10** [comment] 2018-03-13 14:58
You're welcome @shawnbuso ,
I hope that don't will be any problems. :)
Thanks for your help.
 
A.

**Comment by shawnbuso** [comment] 2018-06-12 13:58
I haven't been able to get my hands on a Samsung device that old, and since this is working with the Android Oreo release, I'm going to close this as obsolete. If you're still seeing this issue with a more modern browser and Android OS let me know.

**Closed by shawnbuso** 2018-06-12 13:58 UTC
Labels: support
