### ISSUE TITLE
update videojs dep

### ISSUE THREAD

**Issue by sndrs** [googleads/videojs-ima#333] opened 2017-02-14 13:45 UTC
videojs is currently at `5.16`, but ima still has a dep of `~5.3`. caught it because we found webpack was bundling 2 versions of videojs (our version and ima's).

do you plan to bump the dep at all? we can downgrade our own version, but it means missing out on the improvements...

thanks!

**Comment by SiAdcock** [comment] 2017-02-14 14:00
According to #182, `videojs-contrib-ads` only supports up to 5.3. However, it appears that `video-contrib-ads` [now supports `video.js@^5.10.1`](https://github.com/videojs/videojs-contrib-ads/blob/master/package.json#L129)

Was this the only blocker to updating?

**Comment by shawnbuso** [comment] 2017-02-14 19:08
contrib-ads is one blocker, but we also need to do extensive manual testing to ensure that we don't have any compatibility issues with the new VJS or contrib-ads. I'll make this an FR to update to the latest VJS supported by contrib-ads.

**Comment by Chinese1904** [comment] 2017-02-15 22:35
What are the chances of your plugin being able to work with newer VJS versions soon, like VJS 5.16 and even 6? We would love to use this but also being able to use a newer VJS version. Any timeline on any of this? Would really appreciate any info :-)

**Comment by shawnbuso** [comment] 2017-02-22 18:04
I unfortunately don't have a timeline as of yet, but if you do test with new version feel free to report back with your results. Thanks!

**Comment by shawnbuso** [comment] 2017-05-31 14:16
Duplicate of #383

**Closed by shawnbuso** 2017-05-31 14:16 UTC
Labels: feature request
