### ISSUE TITLE
Unwanted additional player opening in iOS

### ISSUE THREAD

**Issue by nickersonr** [googleads/videojs-ima#746] opened 2018-09-28 19:14 UTC
I'm at my wit's end trying to figure this out. I'm implementing a player to show a fullscreen preroll ad and video upon a click in a react component. Everything seems to be working fine except in iOS/mobile Safari where I get an additional fullscreen empty player window that appears over the rest of my app and does nothing. Clicking play on this player window doesn't play anything and it just stays on top of everything and never plays a video. My properly styled `<video>` tag is correctly playing the preroll and then the video in the background, and I have to close this additional, empty player to see it.

Mostly the code below is lifted directly from the autoplay example. I'm sure there's something simple I'm missing here, but I cannot figure it out. I've tried several different combinations of options, but since those only affect the expected player instance it doesn't address the real problem of preventing this other unwanted player window from showing up on top of everything.

I'm assuming there are some other options available to pass into ima, but I cannot find those detailed anywhere either. What am I missing? Thanks!

**Note:** I am setting `autoplay: true` and `mute: true` manually since `canAutoPlay` seems to always report that it's ok to autoplay unmuted on iOS, which it's generally not.

**Imports from my html template:**
```javascript
<!-- videojs-ima -->
<link rel="stylesheet" href="//googleads.github.io/videojs-ima/node_modules/video.js/dist/video-js.min.css" />
<link rel="stylesheet" href="//googleads.github.io/videojs-ima/node_modules/videojs-contrib-ads/dist/videojs.ads.css" />
<link rel="stylesheet" href="//googleads.github.io/videojs-ima/dist/videojs.ima.css" />

<script src="//googleads.github.io/videojs-ima/node_modules/video.js/dist/video.min.js"></script>
<script src="//imasdk.googleapis.com/js/sdkloader/ima3.js"></script>
<script src="//googleads.github.io/videojs-ima/node_modules/videojs-contrib-ads/dist/videojs.ads.min.js"></script>
<script src="//googleads.github.io/videojs-ima/dist/videojs.ima.js"></script>
<!-- end videojs-ima -->
```

**The react component:**
```javascript
import React from "react";
import canAutoPlay from "can-autoplay";

class VideoButton extends React.Component {
    constructor(props) {
        super(props);

        this.startEvent = "click";
        this.autoplayAllowed = false;
        this.autoplayRequiresMute = false;

        this.state = {
            showAdWindow: false,
        };

        this.openAdWindow = this.openAdWindow.bind(this);
    }

    openAdWindow() {
        this.setState({
            showAdWindow: true,
        });

        this.checkUnmutedAutoplaySupport();
    }

    adTagUrl() {
        // omitted from example, but correctly returns VAST XML
    }

    checkUnmutedAutoplaySupport() {
        canAutoPlay
            .video({ timeout: 100, muted: false })
            .then(({ result, error }) => {
                if (result === false) {
                    // Unmuted autoplay is not allowed.
                    this.checkMutedAutoplaySupport();
                } else {
                    // Unmuted autoplay is allowed.
                    this.autoplayAllowed = true;
                    this.autoplayRequiresMute = false;
                    this.initPlayer();
                }
            });
    }

    checkMutedAutoplaySupport() {
        canAutoPlay
            .video({ timeout: 100, muted: true })
            .then(({ result, error }) => {
                if (result === false) {
                    // Muted autoplay is not allowed.
                    this.autoplayAllowed = false;
                    this.autoplayRequiresMute = false;
                } else {
                    // Muted autoplay is allowed.
                    this.autoplayAllowed = true;
                    this.autoplayRequiresMute = true;
                }
                this.initPlayer();
            });
    }

    initPlayer() {
        const vjsOptions = {
            autoplay: true, // this.autoplayAllowed,
            muted: true,    // this.autoplayRequiresMute,
            debug: true,
        };
        this.player = window.videojs("content_video", vjsOptions);

        const imaOptions = {
            adTagUrl: this.adTagUrl(), // call not included in example, but it works
            id: "content_video",
        };
        this.player.ima(imaOptions);

        if (!this.autoplayAllowed) {
            if (navigator.userAgent.match(/iPhone/i)
                || navigator.userAgent.match(/iPad/i)
                || navigator.userAgent.match(/Android/i)) {
                this.startEvent = "touchend";
            }

            this.wrapperDiv = document.getElementById("content_video");
            this.wrapperDiv.addEventListener(this.startEvent, this.initAdDisplayContainer);
        }
    }

    initAdDisplayContainer() {
        this.player.ima.initializeAdDisplayContainer();
        this.wrapperDiv.removeEventListener(this.startEvent, this.initAdDisplayContainer);
    }

    render() {
        const { showAdWindow } = this.state;
        const videoStyle = showAdWindow
            ? {
                display: "block",
                position: "fixed",
                left: 0,
                top: 0,
                height: "100%",
                width: "100%",
            }
            : { display: "none" };

        return (
            <div>
                <div
                    onClick={this.openAdWindow}
                    role="button"
                    tabIndex={0}
                >
                    <p>Launch Video</p>
                </div>
                <video
                    id="content_video"
                    className="video-js"
                    style={videoStyle}
                    preload="auto"
                    playsInline
                    controls
                >
                    <source
                        src="//commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4"
                        type="video/mp4"
                    />
                </video>
            </div>
        );
    }
}

export default VideoButton;
```

**Comment by webshooter** [comment] 2018-10-01 17:14
**Update**
I'm the OP here, I couldn't modify/update my post from my work account for some reason. I created a simple, non-react html/js version of the autoplay example in our staging domain and I'm still getting the same behavior on iOS. The `video` element correctly loads and plays the preroll ads and main video, but it is hidden under an empty, blank, fullscreen player interface that opens on top of everything. I've included the full html/js example files (see below), but they are essentially just the autoplay example code. The only thing we're doing differently is starting the `video` element as `display: none`, then removing that css and calling `checkUnmutedAutoplaySupport()` to kick of the video play process.

I've also tried dynamically creating the `video` element on the button click (instead of hiding/showing), as well as just leaving it on the page as-is, all with the same results.

I was reading Issue #596 (https://github.com/googleads/videojs-ima/issues/596), which seems related to the behavior I'm seeing, but that was handled and marked as resolved back in May 2018. If anyone has any ideas, please let me know. For now I suppose I'm just going to have to crack open the code and start tracing through to see what might be opening this empty player. Thanks.

**Pastebin links:**
`index.html`: https://pastebin.com/dLvVYxz2
`./js/ads.js`: https://pastebin.com/ic6A3XK8

**Comment by dilburt** [comment] 2018-10-02 01:51
This is a known problem with iPhone/iOS. They have a default video player that grabs all inline video causing all sorts of problems for anyone trying to implement normal video interactions.

Apple has provided a parameter than can help with this. You need to place the parameter on the video source as follows:

**Comment by webshooter** [comment] 2018-10-02 17:04
@dilburt Thanks for the response! I do already have playsinline set for the video tag in my react code (see above) as well as in my test page that is simply the html/js files from the autoplay example. The player window still opens even when this is correctly set, but only when I call `checkUnmutedAutoplaySupport()` in a button click handler. If I just let that call execute as part of the page load the unwanted player window does not show. I'd like to keep it from showing even on the button click workflow.

Side note: I don't know why github will not let me comment on or edit this post using the account I originally created it with, my work account.

**Comment by webshooter** [comment] 2018-10-03 18:17
I'm just going to have to assume that this is indeed a bug. I've had to create a workaround that pushes my users to a new page, shows them the ads/video and then moves them back to their original location. It's more fragile and not ideal, but it is working for now. I'd really like to simply show them the video on the same page using a button click without having the empty fullscreen player show up over everything.

If you want to see this bug in action I have copied the autoplay example code into two different codepens, one that starts playing the video upon load as usual, and one where I have just moved the call to `checkUnmutedAutoplaySupport()` into a button click handler. If you visit these using mobile safari (I am using and iPhone X, safari version 11.4) you will see the the behavior I've been describing.

Note that I have forced `autoplay: true` and `muted: true` since `can-autoplay` incorrectly determines that it cannot autoplay muted in mobile safari. Also, if you see something that I'm doing wrong in regards to getting the code to show the way I've describe, please let me know!

**Autoplay Example No Button:** https://codepen.io/nickersonr/pen/ZqQgPW
Expected behavior: Video loads and autoplays inline when the page loads.
Actual behavior: Video loads and autoplays inline when the page loads.

**Autoplay Example With Button:** https://codepen.io/nickersonr/pen/KGzPMz
Expected behavior: Video loads and autoplays inline when the play button is clicked.
Actual behavior: Video loads and autoplays inline when the page loads. An additional fullscreen player window opens on top of the page with no content and blocks the page and video playing behind it.

**Comment by Kiro705** [comment] 2019-10-24 13:00
Hi all,

I think the solution to this is adding `disableCustomPlaybackForIOS10Plus: true` to your `vjsOptions` like in the example below, and add the `playsinline` attribute on video tag.

```
const vjsOptions = {
            autoplay: true, // this.autoplayAllowed,
            muted: true,    // this.autoplayRequiresMute,
            debug: true,
            disableCustomPlaybackForIOS10Plus: true,
 };
```

Let me know if that works for you, or if I am missing something.

I am going to close this issue, but feel free to reopen if anything related comes up.

**Closed by Kiro705** 2019-10-24 13:00 UTC
