### ISSUE TITLE
Ad request timeout, Empty Vast.. causing VMAP execution to stop

### ISSUE THREAD

**Issue by Slind14** [googleads/videojs-ima#671] opened 2018-06-21 15:16 UTC
When an error occurs during the execution of a vmap entries (I only use vast tags) the whole vmap execution seems to be stopped. Is this intended? It would be great if it would continue with the other vmap entries.

**Comment by shawnbuso** [comment] 2018-06-21 17:02
This is not the intended behavior - can you share your tag with me so I can investigate? Thanks!

**Comment by Slind14** [comment] 2018-06-21 19:13
I always have the issue that these are programmatic tags and it only happens rarely (like once every 10-20 times). How can we go about this? Can we retrieve the "last" vast body error? Are those static so that they can be used for reproduction?

**Comment by shawnbuso** [comment] 2018-06-21 19:17
If you can save the VAST responses we can use that, but unfortunately the IMA SDK doesn't expose them via an API - you'd need to grab them from a proxy or the browser's network tab when you see the issue. If you're able to share your tag I can test on my end and see if I can get the error to occur.

**Comment by Slind14** [comment] 2018-06-21 20:48
Hmm, this will be difficult. How do I know which request it was? I'm using vmap and vast waterfalls.

**Comment by shawnbuso** [comment] 2018-06-21 20:50
We can start with the initial request - the one you provide to your plugin as the adTagUrl option.

**Comment by Slind14** [comment] 2018-06-21 20:52
The issue I see is to reproduce (trying to get) just that one campaign. Especially with different cookies, geo..

**Comment by shawnbuso** [comment] 2018-06-25 13:49
Ah ok - so it looks like when you are getting VAST back, it's empty. This isn't something we can help with, since it's an issue with your ad server setup / inventory and not the implementation itself. For the pubads.g.doubleclick.net tag, I would recommend reaching out to the folks on the [DFP support forum](https://productforums.google.com/forum/#!forum/dfp). It looks like you also have a tag from vh.adscale.de - for that issue you'll need to reach out to the ad scale folks via their support channels.

**Comment by Slind14** [comment] 2018-06-25 16:40
@shawnbuso yes, I have a waterfall/vmap setup for this exact reason, the issue is that it doesn't finish these and throws this error, as if there is some sort of limit or one redirect going too deep.

**Comment by shawnbuso** [comment] 2018-06-25 17:22
VMAP is just used for scheduling ad breaks - it lets you say "play a pre-roll, then an add at 3 minutes, then..." etc. But it won't do anything to mitigate empty VAST responses. If you have a pod of ads with an empty response, it will request and play the next ad in the pod. Also, all VMAP errors are wrapped in a LOG event type so as to not act like a fatal error. So if you're seeing an AdError fire, it is not coming from a VMAP response, but a single ad request.

I'm also not seeing anything in your responses that would indicate waterfall - for DFP waterfall, one of your responses should be a wrapper, and in that outer response you'd have the waterfall extension:

```
<Extension type="waterfall" fallback_index="0"/>
```

Can you ask the DFP folks to take a look and make sure your waterfall settings are configured properly?

**Comment by Slind14** [comment] 2018-06-25 17:36
I have a vmap which has tags to vast waterfalls. e.g. https://api.assertcom.de/videoads/?h=360px&w=640px&pageurl=&referrer=&uuid=7a1426e4-9785-4e29-a746-faf74d338293&type=vmap&ads=2

**Comment by shawnbuso** [comment] 2018-06-25 19:40
If you're getting the error you're seeing above, it means the SDK as exhausted all avenues you've provided to try to get to an ad, and it doesn't have anything left to try. The only thing that could be getting in the way at this point is your max redirects setting, which you can change with the numRedirects plugin setting. If that were the issue, however, you should be seeing a [302 VAST_TOO_MANY_REDIRECTS](https://developers.google.com/interactive-media-ads/docs/sdks/html5/v3/apis#ima.AdError.ErrorCode.VAST_TOO_MANY_REDIRECTS) error, not a 303 error. At this point I would recommend reaching out to your ad serving folks (DFP or ad scale) to ask them to look into your serving settings to see why you're ultimately arriving at empty VAST after exhausting all of your redirects and fallbacks.

**Comment by Slind14** [comment] 2018-06-26 19:18
I see. From the looks of the network console it looks like it is aborting further vmap calls that haven't started when the first vast waterfall goes without fill. Hence I thought/think something is wrong.

**Comment by Slind14** [comment] 2018-06-26 19:24
I'm also usually getting the `ALL_ADS_COMPLETED` when there was no ad/fill instead of the error.

**Comment by Slind14** [comment] 2018-06-27 20:48
Yeah, I'm sure now. I had a few cases where this error appeared during first few seconds. It requires a lot more time to go through the waterfall.

**Comment by shawnbuso** [comment] 2018-07-09 20:30
Would you be able to capture a network log showing this behavior so I can try to figure out what's going wrong? Thanks!

**Comment by Slind14** [comment] 2018-07-09 20:38
HAR snapshot? 
I can try to reproduce it.

**Comment by shawnbuso** [comment] 2018-07-10 14:02
Yea, anything that shows me the URLs being requested and the responses they send back will work. Thanks!

**Comment by shawnbuso** [comment] 2018-07-26 17:56
It's been a while since we've heard from you, so I'm going to close this out. If you still need help feel free to reply here and we'll re-open it. Thanks!

**Closed by shawnbuso** 2018-07-26 17:56 UTC
Labels: support
