### ISSUE TITLE
playlist not autoplay on browser?

### ISSUE THREAD

**Issue by Sudhakar-Sukumar** [googleads/videojs-ima#495] opened 2018-01-30 05:03 UTC
Hi

How can we autoplay the video. once first video completed how shall we make autoplay the next vidoe for the below demo video?
https://googleads.github.io/videojs-ima/examples/playlist/

**Comment by shawnbuso** [comment] 2018-01-30 19:20
Hi there - this sounds like a duplicate of #493. Can we use that thread to address this? Thanks!

**Closed** 2018-02-07 20:03 UTC
Labels: support
