### ISSUE TITLE
a.g.canPlayType is not a function

### ISSUE THREAD

**Issue by swaraasolutions** [googleads/videojs-ima#720] opened 2018-08-07 15:13 UTC
Whenever we are trying to load videojs with ima plugin it seems to be throwing this error message and it is related to ima3.js

I have tried disabling autoplay and disable mute etc but none of it has worked

![imaerror](https://user-images.githubusercontent.com/12116208/43784781-8c365db0-9a82-11e8-9be5-88efded3f4fe.png)

Can you please help out

Thanks

**Comment by ypavlotsky** [comment] 2018-08-15 19:56
Hi,

I need more context to understand this error. Do you have a sample page I can look at? Have you taken a look at our [examples](http://googleads.github.io/videojs-ima/examples/) to see if you've missed something in your integration?

Thanks!
--Yury

**Comment by dpduong90** [comment] 2018-08-24 07:53
I have the same problem. But only didn't work on mobile web, the web pc still work.
Example: http://103.206.217.194:7277/am-nhac/ariana-grande-performs-god-is-a-woman-2018-mtv-video-music-awards_video1031807331267051520.html

Thanks for support!

**Comment by colu75** [comment] 2018-09-17 13:58
Hi, I´ m also having this error, in my case is in iphone/ipad, works ok on android and desktop. 
Im using video.js pulgin.
Here´s an example http://uxina.com.ar/testvideoads/test-banners2.html
![image](https://user-images.githubusercontent.com/13487219/45627490-6e053400-ba68-11e8-916d-95598ccf51f3.png)
IIs there any solution
Thanks in advance

**Comment by cicoph** [comment] 2018-12-18 13:02
> Hi, I´ m also having this error, in my case is in iphone/ipad, works ok on android and desktop.
> Im using video.js pulgin.
> Here´s an example http://uxina.com.ar/testvideoads/test-banners2.html
> ![image](https://user-images.githubusercontent.com/13487219/45627490-6e053400-ba68-11e8-916d-95598ccf51f3.png)
> IIs there any solution
> Thanks in advance

I think it is only an error for youtube video.... rights?

**Comment by cicoph** [comment] 2018-12-18 14:06
The youtube plugin have this function:
  Youtube.isSupported = function() {
    return true;
  };

  Youtube.canPlaySource = function(e) {
    return Youtube.canPlayType(e.type);
  };

  Youtube.canPlayType = function(e) {
    return (e === 'video/youtube');
  };
I think that the error is here. What do you think?

**Comment by cicoph** [comment] 2018-12-18 17:43
If I use a mp4 video it works...

**Comment by Kiro705** [comment] 2019-10-22 14:51
Hi all,

It is my understanding that this specific error is no longer occurring on iOS. 

However web iOS with the Youtube plugin is also not currently working as intended. We are aware of this and working on a fix.

For now I will be closing this issue related to the `a.g.canPlayType is not a function` error.

**Closed by Kiro705** 2019-10-22 14:51 UTC
Labels: support
