### ISSUE TITLE
Black overlay on top of some ads

### ISSUE THREAD

**Issue by stoicbuddha** [googleads/videojs-ima#457] opened 2017-12-08 22:35 UTC
I have been testing with [this url](https://www.nosey.com/featured/featured/video/59f3661e9fcf706433967ca4) and have discovered, as have several others, that some ads play with a black overlay over them.  I can't pin down any commonalities among the ads, and trying to pull the tags out (tags like [this one](https://svastx.moatads.com/essencevp8352/1003399_-_Google_Play_Store_-_NA_-_US_-_Q4_Gift_Cards_-_Q4_2017-209945495_js.xml?yMoatExchange=1&)) don't result in a black overlay anywhere else.  In fact, using that tag directly doesn't cause the overlay either, so I don't know if something is getting screwy in the interim or what.

I have dug into the iframe that the SDK creates and it looks like it creates a div with a video with `src=unknown` that's the whole width of the player and has a background color of black.  If I throw a `display: none` on it via the inspector, you can see the ad just fine.

The VMAP call is [here](https://api.myspotlight.tv/vmap/59f3661e9fcf706433967ca4/675/380/59f3661e9fcf706433967ca4/https%3A%2F%2Fwww.nosey.com%2Ffeatured%2Ffeatured%2Fvideo%2F59f3661e9fcf706433967ca4)

There are at least 3 people on my team who have seen this happening, so I know it's not a one-off.

**Comment by shawnbuso** [comment] 2017-12-11 15:08
We've had a few reports of this but unfortunately haven't been able to reliably reproduce it yet, which makes it difficult to debug. I'll take a look with your tag and see if I can get it to happen. If I see it happen and can save the VAST response that caused it I might be able to reproduce it continuously, in which case we should be able to get it resolved.

**Comment by marguinbc** [comment] 2017-12-11 15:20
@shawnbuso, this might be the div videojs-contrib-ads (used to) create to prevent content flash on some devices, most notably iOS. This was recently released with this PR https://github.com/videojs/videojs-contrib-ads/commit/466f9fcbad2510e1aba9f8ccd52bf56a56e28ee6

**Comment by shawnbuso** [comment] 2017-12-11 15:23
Good to know, thanks - I can look into that as well. We were also occasionally seeing something like this in the IMA SDK without the video.js plugin where we were rendering our linear video ad player on top of VPAID ads, but we weren't able to repro it outside of user feedback. That's the issue I was referencing above.

**Comment by stoicbuddha** [comment] 2017-12-14 19:05
Has there been any update on this?  Were you guys able to recreate the issue on your end?

**Comment by shawnbuso** [comment] 2017-12-14 19:07
I'm having trouble replicating this here - do you have any specific OS and browser combos where you see it that we can try out?

**Comment by stoicbuddha** [comment] 2017-12-14 19:11
I'm on Mac Sierra w/ Chrome 62, and that's where I've seen it.  It isn't something that happens every single time.  I've had to refresh the page a couple of times to see it.  The video has several midrolls, so scrubbing through will give you a better chance without having to constantly refresh.

**Comment by shawnbuso** [comment] 2017-12-15 15:50
OK I'll keep trying to debug this one but I'm still not having any luck :/ I spent about 5 minutes refreshing the page and saw maybe 50 ads, but none of them were hidden.

**Comment by shawnbuso** [comment] 2018-02-07 19:52
@stoicbuddha are you still seeing this issue? If so have you found a way to reproduce it more reliably? Thanks!

**Comment by shawnbuso** [comment] 2018-03-05 19:37
I'm going to close this out since we haven't heard from you in a while - if this is still an issue for you feel free to re-open or start a new issue. Thanks!

**Closed by shawnbuso** 2018-03-05 19:37 UTC
Labels: IMA issue, P2

**Comment by aebenw** [comment] 2020-03-09 21:23
Hey @shawnbuso I'm seeing this issue currently and I think it has to do with your comment above, that there are 2 videos being loaded. 

<img width="1326" alt="Screen Shot 2020-03-09 at 5 17 59 PM" src="https://user-images.githubusercontent.com/39322890/76258742-894e9b00-622a-11ea-9f92-d3cfee736403.png">

If I place the top video as display none, the back screen disappears. Any update on this issue or any way to not load the linear ad alongside the creative?
