### ISSUE TITLE
Ad not autoplay in new version of Google Chrome

### ISSUE THREAD

**Issue by taniabarreira** [googleads/videojs-ima#604] opened 2018-05-08 14:22 UTC
Hi,

My ads after April of 2018 because Autoplay Policy Changes of Google Chrome, don't autoplay.

My ads call two iframes, in the first allow autoplay, but the second one, not, you can see in:
http://rr.sapo.pt/videojs/imagoogle2.html

My player is videoJs, ad plugin is Google IMA...

Can help me?
Thanks

**Comment by taniabarreira** [comment] 2018-05-08 15:29
Hi @shawnbuso ,

Thanks for quick response;
yes, the ad tag return ads vast, but generate  DOMException: play() failed because the user didn't interact with the document first. https://goo.gl/xX8pDD

![capture](https://user-images.githubusercontent.com/25637100/39766767-f16d7c38-52dc-11e8-9340-feda6dd48340.JPG)

**Comment by shawnbuso** [comment] 2018-05-08 15:38
Hmm ok it is still working for me on my Macbook, but I will test on Windows as soon as I am able.

**Comment by taniabarreira** [comment] 2018-05-08 15:39
Thanks a lot @shawnbuso

**Comment by taniabarreira** [comment] 2018-05-09 07:56
@shawnbuso , I not know if has relation, but this problem apparently only occurs with ad tag vpaid, if ag tag is vast, run perfectly...

**Comment by taniabarreira** [comment] 2018-05-09 10:11
@shawnbuso , i replicated your sample of autoplay, but only changed ad tag for my, and error continues...
http://rr.sapo.pt/videojs/index.html

Maybe the problem is in adtag, not?

**Comment by shawnbuso** [comment] 2018-05-09 17:13
Are you seeing the issue with our [sample vpaid ad](https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/single_ad_samples&ciu_szs=300x250&impl=s&gdfp_req=1&env=vp&output=vast&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ct%3Dlinearvpaid2js&correlator=)? If not then the issue is likely with the VPAID ad you're using. If that's the case, you'll need to reach out to the author of the ad and ask them to fix the issue.

**Comment by taniabarreira** [comment] 2018-05-09 17:17
@shawnbuso no, only with my ad tag, thanks for support!

**Comment by shawnbuso** [comment] 2018-05-09 20:02
Hmm I'm still not able to reproduce this one - I tried your test page on my Windows machine and I still get ads autoplaying without error. Can you make sure that the iframes have `allow="autoplay"`

**Comment by taniabarreira** [comment] 2018-05-09 20:50
@shawnbuso , In case of error, i have a first iframe with allow="autoplay", and inside this iframe, i've second an iframe, that don't have allow="autoplay".
My objective is try put allow="autoplay" in that second iframe.

**Comment by shawnbuso** [comment] 2018-05-09 21:11
Which iframe are you referring to when you say "second iframe"? When I look at your sample page I see 6 iframes by the time the ad starts playing.

**Comment by taniabarreira** [comment] 2018-05-10 07:52
@shawnbuso , maybe this print help to understand
![print_rr](https://user-images.githubusercontent.com/25637100/39858739-64933ad8-542f-11e8-9420-8749e954ba8a.JPG)

**Comment by shawnbuso** [comment] 2018-05-10 16:56
Aha ok - I believe that is part of the IMA SDK's VPAID implementation. I'll talk to the team and see if we can get `allow="autoplay"` added to that iframe.

**Comment by taniabarreira** [comment] 2018-05-10 17:07
thanks a lot @shawnbuso

**Comment by taniabarreira** [comment] 2018-05-16 10:15
Hi @shawnbuso , you have news from IMA team?
Thank you

**Comment by shawnbuso** [comment] 2018-05-16 13:36
Yes, they have made this change and it will be included in the next release of the SDK.

**Comment by taniabarreira** [comment] 2018-05-16 14:32
ok, thank you @shawnbuso 
You know when is release new sdk?

**Comment by shawnbuso** [comment] 2018-05-16 15:27
Unfortunately I don't have a definite timline, but hopefully some time within the next week.

**Comment by taniabarreira** [comment] 2018-05-16 16:30
ok, thank you @shawnbuso , if you have more information, can tell me?
Thank you so much for attention and support

**Comment by shawnbuso** [comment] 2018-05-16 17:11
Yep, I'll update here when that goes live.

**Comment by colinrgodsey** [comment] 2018-05-30 16:09
also seeing this issue with our VPAID based player. Oddly enough, when using the google VAST Suite tester, the ad will load with copy-pasted VAST, but it wont from URL for the reasons listed above. Our player uses IMA internally too, so maybe this is a "IMA loading IMA" issue. Anyways, hope the fix works. We'll be waiting for it. Attaching a SS of the the iframe "stack", the middle one doesnt pass the "allow autoplay", and afaik thats an iframe made by IMA:

![screen shot 2018-05-30 at 10 00 53 am](https://user-images.githubusercontent.com/535083/40732854-8420c7b8-63f1-11e8-95c4-774c93366ed9.png)

**Comment by shawnbuso** [comment] 2018-05-30 17:10
The fix for this is live as of 5/15, so you should no longer be seeing the issue.

You should avoid loading IMA within IMA where possible - it's adding another layer of unnecessary complication.

**Comment by colinrgodsey** [comment] 2018-05-30 17:16
@shawnbuso is there any way to influence that middle iframe that i highlighted there? Even without using IAM internally for our VPAID player, it still looks like the VPAID loader is not setting allow=autoplay. This would still prevent anything inside the VPAID from using autoplay, right?

**Comment by shawnbuso** [comment] 2018-05-30 17:23
Could you share your ad tag with me? Thanks!

**Comment by shawnbuso** [comment] 2018-05-30 17:26
Actually, are you able to replicate this in our [sample player](http://googleads.github.io/videojs-ima/examples/advanced/)? It times out there.

**Comment by colinrgodsey** [comment] 2018-05-30 17:35
Seems to do the same. The logging is a bit weird on that player, but if I put a breakpoint on the error callback, i can see I get the same internal error I was getting on the vast suite test page:

![screen shot 2018-05-30 at 11 33 56 am](https://user-images.githubusercontent.com/535083/40737265-7a6c5636-63fd-11e8-912d-7aa3a9ad4e09.png)

**Comment by colinrgodsey** [comment] 2018-05-30 17:39
looks like the internal iframe structure is the same as before too, where the "vpaid loading" iframe doesnt have the autoplay flag:

![screen shot 2018-05-30 at 11 37 47 am](https://user-images.githubusercontent.com/535083/40737432-f5e99f3a-63fd-11e8-9802-2e96ae1d1bbb.png)

**Comment by shawnbuso** [comment] 2018-05-30 18:04
I'm still having an issue with your tag - if I test it on our sample page linked above it errors out with "VAST media file loading reached a timeout of 8 seconds."

**Comment by colinrgodsey** [comment] 2018-05-30 18:06
Here's a creative that does VPAID wrapping through MOAT:

https://vast.mathtag.com/?debug=1&exch=brx&id=asfasf&sid=111666111&cid=5133627&price=12&protocol_version=1&aid=123&adverid=123

They seem to use some (unknown to me) VPAID magic to play the video file in the content iframe, and not in the "vpaid iframe". Going to dig around through the VPAID spec again... but off the top of your head, do you know what VPAID mechanism they could be using? Seems very strange that you could influence any content outside the VPAID iframe.

**Comment by shawnbuso** [comment] 2018-05-30 18:07
If you set your VPAID mode to INSECURE it can influence the parent page, but it's ENABLED by default which does not allow that.

That most recent tag is working for me, so I can try to see what's going on there.

**Comment by colinrgodsey** [comment] 2018-05-30 18:23
Great, sorry I should have sent you the nocache version. Was a newer creative, might not have gotten to PAO by the time you used that link. 

Here's a screenshot of whatever MOAT is doing (this was on the same simple tester you linked earlier):

![screen shot 2018-05-30 at 12 16 51 pm](https://user-images.githubusercontent.com/535083/40739567-c8d3aea4-6403-11e8-9104-644a5ecd6f1b.png)

They're doing something really strange. That video element is definitely outside the VPAID iframe... I have no idea how thats even possible. 

Sorry to bother you so much about this, it's been hurting our delivery pretty bad and we're at a loss. We would have gone through our AdX rep (we're MediaMath, a DSP partner), but I feel like this tech might be too far removed from that team...

**Comment by colinrgodsey** [comment] 2018-06-01 13:36
@shawnbuso sorry to bug you, any new findings here? We're trying to determine our best next course of action, just wanted to get a feel for this issue and if theres been anything obvious thats stuck out so far. thanks!

**Comment by shawnbuso** [comment] 2018-06-06 13:57
Hi there - I do have an update, actually. It looks like we were only setting `allow="autoplay"` when the VPAID mode was INSECURE, and the plugin defaults to ENABLED. We made a change to the IMA SDK to fix this, but it hasn't been included in a release yet. It should be live in the next IMA SDK release, which the plugin will pick up automatically at runtime.

**Comment by taniabarreira** [comment] 2018-06-06 14:27
Ok @shawnbuso , thanks a lot for support!

**Comment by colinrgodsey** [comment] 2018-06-06 14:55
@shawnbuso thanks for the update and support! 🍰

**Comment by shawnbuso** [comment] 2018-06-12 14:08
Hi all,

The fix to add `allow=autoplay `on the iframe went live last Friday. This was a fix to the underlying IMA SDK, and the plugin picks that up automatically, so you don't need to do anything to upgrade to see this fix. Let me know if you're still seeing an issue.

Thanks,
Shawn

**Comment by taniabarreira** [comment] 2018-06-12 16:00
Ok @shawnbuso , one more time, thanks a lot for support!

**Closed** 2018-06-18 15:39 UTC
Labels: IMA issue
