### ISSUE TITLE
Ads do not play on Android

### ISSUE THREAD

**Issue by stoicbuddha** [googleads/videojs-ima#325] opened 2017-01-20 22:11 UTC
In order to implement ads, we have to call `player.play()` at various points to trigger ads loading, etc.  Anyway, Chrome for Android doesn't much appreciate this, so we can't get ads to play in Android, even without autoplay.  It could be an issue with my implementation, but since it works everywhere else (including iOS, which is set to autoplay), I can't be sure.

http://player.dotstudiopro.com/share/54c5ea2d97f815fa400f941d?targetelm=.player&companykey=54c55c3e97f815132d561f12&loopplayback=false&autostart=false&muteonstart=false&enablesharing=false&disablepaywall=1423689480&skin=228b22

This is our current implementation.

**Comment by stoicbuddha** [comment] 2017-01-20 22:12
Note that the video will likely play for a moment before ads; that's an unrelated issue.

**Comment by shawnbuso** [comment] 2017-01-23 15:34
Hi there,

I tested that page on Android, iOS, and desktop and I didn't see ads on any platform, just content. Could you point me to your implementation code so I can see how you've implemented?

Thanks,
Shawn

**Comment by stoicbuddha** [comment] 2017-01-23 17:18
Our ad server was having issues.  Should be good to go now.

**Comment by shawnbuso** [comment] 2017-01-24 18:30
OK I'm able to replicate now, but oddly I'm not getting any errors in the logs. Would you be able to 

a) Enable debug mode in the video.js plugin settings
and
b) Load ima3_debug.js instead of ima3.js

That will increase the log level and hopefully something there will stand out. Thanks!

**Comment by JHGitty** [comment] 2017-01-26 20:38
I have the same issue - only on Chrome @ Android. I think the issue is this line in the console on mobile device (seen through Remote Device feature of Google Chrome):

Failed to execute 'play' on 'HTMLMediaElement': API can only be initiated by a user gesture.

We do the same as in the example:
player.one(startEvent, function() {
            player.ima.initializeAdDisplayContainer();
            player.ima.requestAds();
            player.play();
        });

**Comment by JHGitty** [comment] 2017-01-26 21:04
Did you forgot to remove the controls from "content_video_html5_api"? See example file.

**Comment by stoicbuddha** [comment] 2017-01-26 21:40
@shawnbuso ima3_debug.js is now being pulled and I've confirmed I'm seeing more debug info that appears to be from the ima script.

**Comment by stoicbuddha** [comment] 2017-01-26 21:41
@JHGitty I'm not sure I understand.  I am not doing anything with anything named `content_video_html5_api` and I haven't seen it pop up anywhere.

**Comment by shawnbuso** [comment] 2017-01-27 15:02
I took another look at your implementation and I'm not sure what's causing it, but ultimately the ad media is timing out. It looks like you're doing a *lot* of custom things with the IMA plugin - would it make more sense to do your own IMA implementation on top of the video player? The plugin here is somewhat designed to be a black box, and if you need a lot of customization it might be easier for you to just handle the implementation for yourself. You can see our documentation on that [here](https://developers.google.com/interactive-media-ads/docs/sdks/html5/quickstart) - you'd just need to substitute the video.js player's video element for the video element we use in the examples.

**Comment by stoicbuddha** [comment] 2017-01-31 17:56
@shawnbuso What do you mean by "black box"?

Also, I don't do a lot of custom stuff.  I mostly try to make sure the player doesn't play before the ad, and get the display set up correctly again on ad errors/complete/timeout/etc.  What were you seeing that lead you to that conclusion?

**Comment by shawnbuso** [comment] 2017-01-31 18:25
"Black box" would mean that you shouldn't have to worry about the details of the implementation too much - you just provide the inputs (source, ad tag, etc.) and it gives you the desired output.

I was mainly going off of your comment that "[you] have to call player.play() at various points to trigger ads loading, etc." which is not really how the plugin was designed to be used. You are of course welcome to use the plugin if you want, I was just suggesting that it might actually be easier to do your own IMA implementation and not have to worry about getting the IMA plugin to fit your particular implementation's needs.

**Comment by shawnbuso** [comment] 2017-02-09 17:15
I'm going to close this issue since it's been more than a week, but if you still need help feel free to re-open. Thanks!

**Closed by shawnbuso** 2017-02-09 17:15 UTC
Labels: awaiting_response, support

**Comment by stoicbuddha** [comment] 2017-02-09 17:24
I discovered a fix on our end.  It was a leftover from our previous implementation.  So this a non-issue.

**Comment by pangia** [comment] 2018-06-24 04:52
@stoicbuddha what was the solution for this. I am facing the exact same thing. Ads show fine on any platform except Android, where they all timeout.
