### ISSUE TITLE
No resume on iOS after pre-roll ends if stream is HLS

### ISSUE THREAD

**Issue by dolartoday** [googleads/videojs-ima#71] opened 2015-03-19 19:39 UTC
I was able to fix for desktops by listening to the 'adend' event

```
            // What happens after an ad is shown?
            player.on('adend', function() {
                    player.load();
                    player.play();
            });
```

However, on mobile (iOS to be specific) after the pre-roll the live stream will not resume. This issue seems to be specific to LIVE streams as static mp4 do not have this issue.

It seem to be related to the way the plugin handles resuming. An HLS stream needs to be 'loaded' before PLAY, thats why the above code will fix the issue for desktops. I assume, on iOS the adend event never fires and thats why I can not fix it for iOS devices.

Thanks,

**Comment by brkattk** [comment] 2015-08-06 15:54
This seems to be an issue for webkit. I'm having the same issue within a Fire TV web app. Here's the user agent

`Mozilla/5.0 (Linux; Android 4.2.2; AFTM Build/JDQ39) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/34.0.0.0 Mobile Safari/537.36 cordova-amazon-fireos/3.4.0 AmazonWebAppPlatform/3.4.0;2.0`

**Comment by brkattk** [comment] 2015-08-06 19:08
I was able to get around this by doing the following:

```js
player.on('ademptied', function() {
  player.play();
});
```

**Comment by shawnbuso** [comment] 2015-09-21 17:56
Are you folks still seeing this issue? I've testing with a few m3u8 URLs on iPad but it's working OK for me. Is this perhaps specific to iPhone? If you're still seeing it, could you send me the content URL you're using to test and the ad tag?

**Comment by iMark21** [comment] 2015-10-13 09:47
We have the same problem. The video not resume after pre-roll ends

**Comment by brkattk** [comment] 2015-10-13 13:44
I was seeing this issue on the Amazon Fire TV's webkit

**Comment by shawnbuso** [comment] 2015-12-29 18:55
Ah ok the IMA SDK does not support Amazon Fire TV, so that's where the issue is coming from. You can see the compatible devices [here](https://developers.google.com/interactive-media-ads/docs/sdks/html5/compatibility). Are you still seeing the issue on iOS?

**Comment by brkattk** [comment] 2015-12-29 18:58
I was able to get this working properly on Amazon Fire TV. I was just pointing out which version of webkit I had been using

**Comment by shawnbuso** [comment] 2016-01-04 21:47
Going to close this for lack of response from the initial poster. If anyone needs more assistance with this issue feel free to re-open.

**Comment by miraz235** [comment] 2017-10-02 05:32
I has same issue in iPhone. In Desktop, stream video works with ads, but in iPhone after ad play stream video not playing. There shows no error in console. Can you please help me.
I have use,
videojs : 5.20.3
videojs-contrib-hls : 5.11.0
videojs-contrib-ads : 5.1.0
videojs-ima : 0.6.0

You can see here my sample video in iPhone.
- [ad with mp4 video (works)](http://blogsoftdev.no/testvideo/video-iphone.html?ad=true&stream=false)
- [stream video without ads (works)](http://blogsoftdev.no/testvideo/video-iphone.html?ad=false&stream=true)
- [stream video with ads (not works)](http://blogsoftdev.no/testvideo/video-iphone.html?ad=true&stream=true)

**Comment by shawnbuso** [comment] 2017-10-02 14:46
Hi Miraz,

Are you able to repro this in our samples with your content? I tried plugging it in to our simple sample and that works fine on iPhone.

Thanks,
Shawn

**Comment by miraz235** [comment] 2017-10-03 04:08
I use this script and use some sample iPhone content like make a `dumbPlayer` by placeholder on click and run video.
ima plugin option has `nativeControlsForTouch: false`

this iPhone [example](https://googleads.github.io/videojs-ima/examples/iPhone/) works perfectly but it use an `.mp4` video file. But I use  `.m3u8` file also which run by HLS plugin.

```

        function getParameterByName(name, url) {
            if (!url) url = window.location.href;
            name = name.replace(/[\[\]]/g, "\\$&");
            var regex = new RegExp("[?&]" + name + "(=([^&#]*)|&|#|$)"),
                results = regex.exec(url);
            if (!results) return null;
            if (!results[2]) return '';
            return decodeURIComponent(results[2].replace(/\+/g, " "));
        }
        jQuery(function() {
            var ad = getParameterByName('ad') == 'true';
            var stream = getParameterByName('stream') == 'true';
            var $mediaPlaceHolder = $('#media-placeholder').css({
                'background-image': 'url(//s3-us-west-2.amazonaws.com/s.cdpn.io/167883/html5-videojs-rayrcdemo.png)',
                'background-position': 'center',
                'background-size': 'cover',
                'background-repeat': 'no-repeat'
            });
            var player = '';
            var dumbPlayer = document.createElement('video');
            dumbPlayer.id = 'videoSingle';
            dumbPlayer.className = 'video-js vjs-default-skin';
            var contentSrc = document.createElement('source');
            if (stream) {
                contentSrc.setAttribute('src', 'https://s3.amazonaws.com/_bc_dml/example-content/bipbop-advanced/bipbop_16x9_variant.m3u8');
                contentSrc.setAttribute('type', 'application/x-mpegURL');
            } else {
                contentSrc.setAttribute('src', 'http://rmcdn.2mdn.net/Demo/vast_inspector/android.mp4');
                contentSrc.setAttribute('type', 'video/mp4');
            }
            dumbPlayer.appendChild(contentSrc);

            $mediaPlaceHolder.on('click', function() {
                $(this).replaceWith(dumbPlayer);
                player = videojs('videoSingle', {
                    controls: true
                });
                player.ima({
                    id: 'videoSingle',
                    prerollTimeout: 15000,
                    adTagUrl: ad ? 'http://pubads.g.doubleclick.net/gampad/ads?sz=640x480&' +
                        'iu=/124319096/external/single_ad_samples&ciu_szs=300x250&impl=s&' +
                        'gdfp_req=1&env=vp&output=xml_vast2&unviewed_position_start=1&' +
                        'cust_params=sample_ct%3Dlinear%26deployment%3Dgmf-js&correlator=' : null,
                    nativeControlsForTouch: false,
                    debug: true
                });
                player.ima.initializeAdDisplayContainer();

                // Request ads and play the video
                player.ima.requestAds();
                player.play();

            });
        });
    
```

**Comment by shawnbuso** [comment] 2017-10-03 16:35
Ah ok, I think we're having some compatibility issues with the HLS plugin (see #314). I will take a look at this but it may end up being a larger change that requires us to add compatibility with the HLS plugin.

**Comment by miraz235** [comment] 2017-10-04 05:34
Thanks for your clarification.

**Comment by shawnbuso** [comment] 2017-12-20 15:48
Closing since this is now a dupe of #314.

**Closed by shawnbuso** 2017-12-20 15:48 UTC
Labels: support

**Comment by edilashimov** [comment] 2022-10-10 17:04
@shawnbuso Hello I am having an issue with iOS mobile/iPad devices fail to play the content after the preroll has been completed. Happens only with the hls live content not the mp4. Please help. I am trying to cast the content using Chromecast and google IMA Ads.
