### ISSUE TITLE
Video Js - Autoplay IMA Ads issue - Google Chrome

### ISSUE THREAD

**Issue by sudhakarsukumar** [googleads/videojs-ima#654] opened 2018-06-13 08:50 UTC
When we click on the ads or click on the control (paly/pause, mute/unmute), the ad paused and the supposed to play from the first again th eplay button need to be clicked. This occurs only in google chrome browser and when the autoplay is enabled. Could you please help us in this issue. Thanks

**Comment by shawnbuso** [comment] 2018-06-13 13:53
Do you have a sample page where I can reproduce this issue?

**Comment by shawnbuso** [comment] 2018-07-26 17:55
It's been a while since we've heard from you, so I'm going to close this out. If you still need help feel free to reply here :)

**Closed by shawnbuso** 2018-07-26 17:55 UTC
Labels: support
