### ISSUE TITLE
Container showing overlay z-index 1111

### ISSUE THREAD

**Issue by jakubfrydrych** [googleads/videojs-ima#850] opened 2019-10-24 23:55 UTC
Hi, I would like to ask if some parameter in plugin configuration can set another value for z-index of element displaying nonlinear ads.

Or whether it could be somehow set that after the overlay time expires, the element hides and does not remain visible through the player?

The problem arises because the container with the `.ima-ad-container.bumpable-ima-ad-container` css class has a z-index value of 1111, so all surrounding elements need to be re-styled to have a higher value. For example, for the correct function of the big play button. Probably a similar problem was solved in issue # 403, but the discussion did not continue.

![Snímek obrazovky 2019-10-25 v 1 50 13 (2)](https://user-images.githubusercontent.com/34452513/67533465-50be8280-f6ca-11e9-9626-045bba263e90.png)

Thank you in advance for your reply

**Comment by Kiro705** [comment] 2019-10-25 14:46
Hi @jakubfrydrych ,

Thanks for pointing this out.

A work-around I found was to add this css.
```
.ima-ad-container {
    display: none;
}
```
Let me know if that works for you.

I would say expect a fix for this in the next videojs-ima plugin release.

**Comment by jakubfrydrych** [comment] 2019-10-25 18:38
Hi, thank you very much for your reply.

I think this workaround will not work, because the advertising container for some reason has an inline style entry that will probably have the highest specificity of css rules. So you would need to change the style attribute directly on the container programmatically.

So far I have not found out why the container has this value of z-index: 1111.

A little more complicated workaround seems to me to use a timeout with the minSuggestedDuration value for overlay and then hide the ad-container and display the non-linear ads again. The problem will probably distinguish companion from overlay.

Issue # 849 also applies to this topic.

**Comment by Kiro705** [comment] 2019-10-25 19:03
Hi @jakubfrydrych ,

Would you include steps to reproduce or a sample app of the bug?

`display: block` is being added on ad start, but should be being changed to `display: none` when the ad ends.

My fix was for if the container is blocking an overlaying button before the start of a video.

**Comment by Kiro705** [comment] 2019-10-30 14:15
Hi @jakubfrydrych ,

It is my understanding that the `ima-ad-container` is hidden or shown depending on if ads are play or not. You may have found an issue with your player not hiding the container following an ad break.

If you are still experiencing this issue, could you include steps to reproduce and I can take a look at solving the issue?

**Comment by ckybonist** [comment] 2019-11-03 04:19
Hi @Kiro705 

I've found that, If the ad not actually *fill in, then there's no `display: none` in ad container's style.
 
In that moment, entering `fullscreen` mode will cause the videojs-ima add an inline style of width and height matches video container. Due to ad container has high `z-index` and no `display: none`, my video control bar is *unclickable*.

Here's my log:
```
VIDEOJS: ADS: Received nopreroll event
VIDEOJS: ADS: Skipping prerolls due to nopreroll event (BeforePreroll)
VIDEOJS: ADS: Playback was canceled by cancelContentPlay
VIDEOJS: ADS: Received play event (BeforePreroll)
VIDEOJS: ADS: BeforePreroll -> Preroll
VIDEOJS: ADS: Preroll -> ContentPlayback
ADS: Received adsready event (ContentPlayback)
```

Current workaround is:
```scss
.video-js {
  .vjs-control-bar {
    z-index: 9999;
  }
}
```

**Comment by Kiro705** [comment] 2019-11-04 15:11
Hi @ckybonist ,

Could you please let me know the steps to reproduce the unclickable control bar bug?

Right now I have tested or [simple sample app](https://googleads.github.io/videojs-ima/examples/simple/) and was not able to reproduce the issue.

**Comment by ckybonist** [comment] 2019-11-09 06:14
Right now I couldn't reproduce the bug by sample codepen, so I just provide some info first:

#### After enter fullscreen, the ad container's HTML became:
```HTML
<div id="my-video-id_ima-ad-container" class="ad-container" style="position: absolute; z-index: 1111;">
    <div style="position: absolute; width: 678px; height: 381.375px;">
        ...
    </div>
    <div id="polydice-video_ima-controls-div" class="polydice-video_ima-controls-div ima-controls- 
         div" style="width: 100%;">
        ...
    </div>
</div>
```
Why ad-container overlaps my video:
1. Outermost `<div />` has `z-index: 1111`
2. First child `<div />` has `width: 678px; height: 381.375px` which is exactly the video's width and height.

#### videojs options
  
-   fluid: true,
-   controls: true,
-   autoplay: true,
-   muted: true,
-   loop: true,
-   preload: 'metadata',
-   aspectRatio: '16:9',
-   docking: true,
-   playsinline: true

#### videojs-ima options
-  adTagUrl
-  disableCustomPlaybackForIOS10Plus: true
-  adsRenderingSettings: { enablePreloading: true }
-  contribAdsSettings: { debug: true }
-  debug: true

#### I've registered an click/touched event on video player to support autoplay
```js
  let startEvent = 'click';
  if (isMobile()) {
    startEvent = 'touchend';
  }

  videoNode.addEventListener(startEvent, function listener() {
    player.ima.initializeAdDisplayContainer();
  }
```

**Comment by Kiro705** [comment] 2019-11-18 20:51
Hi @ckybonist ,

It sounds like the issue might be with your VMAP if the VAST requests are not getting sent. Are you able to included your VMAP or test it using the [Video Suite Inspector](https://developers.google.com/interactive-media-ads/docs/sdks/html5/vastinspector).

**Comment by ckybonist** [comment] 2019-11-19 06:26
@Kiro705 

I've test my VMAP on Video Suite Inspector and it behaves normally as expected.

**Comment by Kiro705** [comment] 2019-11-19 21:36
Hi @ckybonist ,

I am unable to reproduce your issue. If possible, include steps to reproduce the behavior you are describing or sample code containing the behavior.

**Closed** 2019-12-04 16:41 UTC
Labels: P2, bug
