### ISSUE TITLE
Chrome 66 Preroll (user interaction required) onAdsError causing virtual hang

### ISSUE THREAD

**Issue by mattfrankly** [googleads/videojs-ima#635] opened 2018-06-04 21:51 UTC
**Description**
If using Google ima3 and Chrome 66, when video playback requires user interaction, an adserror is fired, but the videojs player stays in a playing mode - showing pause button instead of play button. Also, the play promise catch doesn't seem to be passed through to original player that asked for the play() call.
video.js version 6.10.1
video-contrib-ads version 6.3.0
videojs-ima version 1.3.0

**Steps to Reproduce**
Here is a simple demonstration of the issue:

http://demo.adtags.mobi.s3-website-us-west-1.amazonaws.com/chrome-66-issue/index.html

If you load the page just by entering url and pressing enter (not using refresh), notice the console.log:

> videojs.ima.js:1385 Ad error: AdError 400: There was an error playing the video ad. Caused by: AdError 1205: The browser prevented playback initiated without user interaction.
> SdkImpl.onAdError @ videojs.ima.js:1385
> video.js:498 VIDEOJS: adserror (Preroll)
> video.js:21363 Uncaught (in promise) DOMException: play() failed because the user didn't interact with the document first. https://goo.gl/xX8pDD

First step
**Expected Results**
Player would give a catch() to the promise - or at least pause the video playback, so user knows that video is not going to play without interaction

![Image](https://user-images.githubusercontent.com/1171541/40868649-705497c2-65aa-11e8-8905-f74ddd91c01b.png)

**Actual Results**
Player is in play mode (see the pause button showing in the player).

**Versions**
videojs-contrib-ads version: 6.3.0

Video-js version: 6.10.1

Other plugins: videojs-ima

**Platforms**
Browsers: Chrome v66
OS/Devices: MacOS (and most likely Windows)

CC: @bill5roses

**Comment by shawnbuso** [comment] 2018-06-05 15:54
Is this on a specific platform? I tested on Chrome 66 on my mac but I do see an ad autoplay, no error in the console.

**Comment by bill5roses** [comment] 2018-06-05 18:12
Hi Shawn, it is not platform specific. If you reload it works, but if you just put the url and enter, then you see the issue. Chrome 66 claims to require user interaction to begin video playback and the <video> element in Chrome has a promise that you can catch when it fails. That promise is not getting passed back through to the original JS. We can get the adserror out, but by then it is too late as .play() is already being called again on the original video and causing the video to be in a playing state, but not actually playing.

**Comment by shawnbuso** [comment] 2018-06-05 21:27
Hm interesting, I can replicate now. I can take a look to see if we can handle this better. In the meantime, have you taken a look at our [autoplay sample](https://github.com/googleads/videojs-ima/tree/master/examples/autoplay)? That has implemented canAutoplay to autoplay when allowed, and fall back to click to play when not allowed.

**Comment by mysuf** [comment] 2018-06-05 23:27
As you probably know, IMA SDK has some silent errors (like skippable on IOS). This could be one of them. Make sure that you call ads.skipLinearAdMode() onContentResumeRequested in case that !ads.inAdBreak()

**Comment by bill5roses** [comment] 2018-06-07 02:54
Hi Shawn, I added can-autoplay.js to the page but still having the same issue. If I go into iOS responsive mode in my chrome desktop browser, then click to play does appear.

The big issue to solve here is to somehow get the player out of the playing mode, so user knows to click to get the video started. Right now it just shows the pause button, like it is playing, but hung because of the user interaction exception... When the exception occurs, it would be great if the plugin would not try to call .play() again, and instead just pause the video. Seems like that would resolve it?

**Comment by shawnbuso** [comment] 2018-06-07 14:17
Do you have a sample page using canAutoplay where I can replicate the issue? If canAutoplay says the page can't be played then the plugin shouldn't be trying to play the video player, so I'm not sure what's causing it to get into that state.

**Comment by bill5roses** [comment] 2018-06-07 16:28
Thanks @shawnbuso, I added canAutoplay to the example code here:
http://demo.adtags.mobi.s3-website-us-west-1.amazonaws.com/chrome-66-issue/useCanAutoplay.html
It checks canAutoplay.video() before even calling to play the ads/video. That seems to work. 
I thought that the plugin also did this somehow internally? If so, why doesn't the example at:
http://demo.adtags.mobi.s3-website-us-west-1.amazonaws.com/chrome-66-issue/index.html
work? It also includes the same canAutoplay.js before calling to play the ad...

I think for us, it will make sense to just use canAutoplay.video() before calling to do playback, just curious why the videojs-ima or videojs-contrib-ads is not handling this too.

**Comment by shawnbuso** [comment] 2018-06-07 17:00
This isn't something that videojs-ima can handle, because we don't actually maintain any player state - we just call `startLinearAdMode` and `endLinearAdMode` from contrib-ads, and they handle things from there. I can't be sure, but it looks like maybe video.js needs to handle this - you call VideojsPlayer.play(), which under the hood calls play() on the vanilla video element. That second play call is what returns a promise, and for some reason that promise isn't being bubbled up to the first play call. I[n the video.js code it looks like it should be returning that promise](https://github.com/videojs/video.js/blob/master/src/js/player.js#L1880), but for whatever reason you're not getting it.

The reason canAutoplay works is that it's not attempting to play the video.js player, it's attempting to play it's own programmatically created video player, which is not wrapped by Video.js.

**Comment by mysuf** [comment] 2018-06-07 19:53
I tested this with my impl and it autoplays ad everytime(even in fresh tab) without can-autoplay. I guess that it could be wrong syncing with contrib-ads states (i.e. async call of player's method during changing player's state?) But its only my guess..

**Comment by shawnbuso** [comment] 2018-06-07 20:39
Hmm interesting - keep in mind also that Chrome doesn't strictly allow / disallow autoplaying video - it uses a Media Engagement Index to determine whether or not video should be allowed to autoplay on a page. So you could see different behavior across different devices or browser sessions.

**Comment by mysuf** [comment] 2018-06-07 20:58
You are absolutly right. I tested it only on 127.0.0.1 and it has probably high trust rate.. Now I tested it with videojs-ima and it works too..

**Comment by shawnbuso** [comment] 2018-06-12 14:06
Hmm ok, so are you still seeing an issue with the videojs-ima plugin? If not I'm going to go ahead and close this issue. Thanks!

**Comment by bill5roses** [comment] 2018-06-12 21:54
Hi Shawn, I think there is some confusion on where the issue lies here. The problem still exists - where when video needs user interaction on Chrome 66, the player gets into a bad state. To avoid that state, we can use canAutoplay() to detect before we even try to call play(), but would be great if the Promise/catch would actually work (videojs supposedly sends the catch when it fails to play when user interaction is needed, but that gets lost somehow either with IMA or contrib-ads or videojs-ima ... As .play() is called again on the ad video, and the catch does not get fired on the original content video...

**Comment by shawnbuso** [comment] 2018-06-13 14:01
Aha ok - if you're calling videojs.play(), then I think the issue would lie with either the video.js player (most likely) or contrib-ads. The IMA plugin isn't doing anything funny around handling or intercepting play() calls, so I don't see what we could be doing to cause the issue you're seeing.

**Comment by bill5roses** [comment] 2018-06-13 14:37
Thanks @shawnbuso, I actually logged the issue with contrib-ads first, but @incompl suggested I log the issue with videojs-ima, see: https://github.com/videojs/videojs-contrib-ads/issues/392
Would you mind commenting on the contrib-ads issue as you are the expert here? :-) 

Thanks!

**Comment by shawnbuso** [comment] 2018-06-13 14:51
Just to summarize, it seems like the root of the issue is that if you call videojs.play(), and the play() is rejected, the player still goes into a "playing" state, with a pause button being shown instead of a play button. Neither the contrib-ads plugin nor the videojs-ima plugin are putting the player in that state, so I think this is ultimately a Video.js player issue.

Aside from that, the contrib-ads pluign doesn't handle autoplay support (as they stated in videojs/videojs-contrib-ads#392), so I think the only way to handle this is to use the canAutoplay method that our autoplay example uses, and only programmatically call videojs.play() when you know that it will not be rejected.

**Comment by gkatsev** [comment] 2018-06-13 20:37
So, looking into this, it does seem like this is a Video.js issue. Though, maybe there's a bug in contrib-ads too? Not sure.
But this is an issue related to how Video.js sets its state and how browsers natively handle autoplay rejection. For example, Safari will trigger a `playing` and `pause` events in the case of a failed autoplay. Chrome, however, doesn't trigger these, and thus the play toggle component of Video.js doesn't know that autoplay has failed.
Given that the Video.js player manually gets `play()` called on it, we can probably attach to the play promise and Do The Right Thing™️. We also, have a revamped autoplay support and better Promise from `play()`  in the pipeline.

**Comment by gkatsev** [comment] 2018-06-13 20:40
A workaround for now would be to just trigger `pause` on the player manually `player.trigger('pause')`.

**Comment by mysuf** [comment] 2018-06-13 20:56
Theoreticaly, when video.js will be able to handle rejected `play()` as well as contrib-ads (I guess that this issue has chaining effect) with fallback to non-autoplay player state, then dependency on can-autoplay could be possibly dropped in future..

**Comment by gkatsev** [comment] 2018-06-13 22:50
Looking at it some more, if I remove the `player.ima()` call from the given example, Video.js handles the play promise rejections correctly.
The behavior in Video.js can definitely be improved but there's also something weird happening if ima and contrib-ads are run on the page.

**Comment by gkatsev** [comment] 2018-06-14 19:33
While trying to make a reduced test case, I think we got to the bottom of this and it is something that we're most likely going to fix in contrib-ads.

**Comment by incompl** [comment] 2018-06-14 19:50
I made a branch of contrib-ads with a potential test, would you mind seeing if this fixes the issue for you? https://github.com/videojs/videojs-contrib-ads/pull/400

**Comment by mysuf** [comment] 2018-06-14 20:32
I have a question. Is correct to fire `readyforpreroll` when it is technically not ready for preroll?

**Comment by incompl** [comment] 2018-06-28 14:58
Have you had a chance to determine if the above fix addresses this issue?

**Comment by Kiro705** [comment] 2019-10-16 14:34
Hi all,

It looks like this issue may have been resolved from the contrib-ads side. I will be closing the issue, but feel free to reopen if the issue still exists.

**Closed by Kiro705** 2019-10-16 14:34 UTC
Labels: support
