### ISSUE TITLE
Changing volume durning ad results in 100% volume on every click

### ISSUE THREAD

**Issue by vincurekf** [googleads/videojs-ima#576] opened 2018-03-22 08:54 UTC
First of all, thanks for this great (and the only working) plugin. :+1: 

But, there is one issue rendering it pretty annoying for end users.
If you play ad and change the volume, every click you make after the change results in volume being set to 1, in the ad AND in the video playing after the ad ends.

I've tracked the error back to [line 335](https://github.com/googleads/videojs-ima/blob/master/src/ad-ui.js#L335) in ad-ui.js.

The problem is that there aren't any checks to find out where the user click, if it's inside the volume controls or not, and so the volume is always set to 1.

My dirty fix was to simply check if the clicked element had id `my-video_ima-slider-level-div` assuming the ID of video element is `my-video` so the IDs match. That fixed it for me but maybe checking for the class would be better. 

I am using the latest version of videojs-ima and videojs version 5.20.5 (as newer versions don't work)

_UPDATE_
This helped and it's working fine, wrap function `AdUi.prototype.changeVolume`:
```js
AdUi.prototype.changeVolume = function (event) {
  if( event.target.classList.contains('ima-slider-level-div') ){ // <- added
    var percent = (event.clientX - this.sliderDiv.getBoundingClientRect().left) / this.sliderDiv.offsetWidth;
    percent *= 100;
    // Bounds value 0-100 if mouse is outside slider region.
    percent = Math.min(Math.max(percent, 0), 100);
    this.sliderLevelDiv.style.width = percent + '%';
    if (this.percent == 0) {
      this.addClass(this.muteDiv, 'ima-muted');
      this.removeClass(this.muteDiv, 'ima-non-muted');
    } else {
      this.addClass(this.muteDiv, 'ima-non-muted');
      this.removeClass(this.muteDiv, 'ima-muted');
    }
    this.controller.setVolume(percent / 100); // 0-1
  } // <- added
};
```

**Comment by ypavlotsky** [comment] 2018-03-22 14:12
Hi,

I do see some issues with clicking on the content video and that affecting the volume, but I want to make sure I'm actually seeing your bug and not some other bug. What are the exact steps to reproduce your issue? I'm when I click on the ad, I actually get the volume being set to 0.

**Comment by vincurekf** [comment] 2018-03-22 16:46
Hi Yuri,
I have been trying to set up example case for the pas hour and I can't even get it to work anymore.
I am sorry I can't be more helpful here. 

The not working example is [here](http://test.meshr.cz/videojs/), I don't know if it's the VAST urls I am using but it's only basic files:
```html
<script src="http://imasdk.googleapis.com/js/sdkloader/ima3.js"></script>
<script src="./videojs/video.js"></script>
<script src="./js/videojs-contrib-ads.js"></script>
<script src="./js/videojs-ima.js"></script>
```
plus css styles.
the initialization script:
```js
(function(){
  videojs('my-video', {
    controls: true,
    responsive: true,
    fluid: true,
  }, function(){
    var player = this;
    player.on('volumechange', function(){
      console.info('volume', player.volume());
    });
    player.ima({
      id: 'my-video',
      adLabel: 'Ad',
      showCountdown: true,
      adTagUrl: '<?php echo $_GET['url']; ?>' //is set via form
    })
  });
})();
```
But the volume value passed to `AdUi.prototype.changeVolume()` is set elsewhere, that I am unable to find out. Maybe there is issue borrowed somewhere deeper.

**Comment by Kiro705** [comment] 2019-10-15 17:02
Hi all,

I am taking a look into this issue and am trouble reproducing. The current videojs-ima plugin does not use the following if statement wrapper :
`if( event.target.classList.contains('ima-slider-level-div') ){`

However I am not able to see this bug. Because of that I am going to close this issue. However, please reopen if this issue does still exist and include steps to reproducing it. I would be very interested in adding a fix for it but need the steps to reproduce.

**Closed by Kiro705** 2019-10-15 17:02 UTC
Labels: P2, bug
