### ISSUE TITLE
Ad pauses if switched to fullscreen mode while ad is running

### ISSUE THREAD

**Issue by Snowbell92** [googleads/videojs-ima#742] opened 2018-09-24 05:13 UTC
I am not sure if this is a bug or this is the intended behavior, but googling did not give me any definite answers.

Steps to reproduce: 

1. go to any content with a pre-roll ad ( I only have pre-roll so that's what I know)

2. ad starts to play, without hitting anything else, hit full-screen button. 

3. player switches to full-screen, but the ad is paused. Weirdly, the play button still have not switched to pause button. 

4. clicking on the play button again (which is still not showing paused state) - will change the icon to paused, I assume switch the player to paused state. 

5. now clicking on the play button will start the ad from start again. 

This behavior only happens once. if you repeat the above steps a second time, you'll see that the player is behaving as expected - the ad isn't getting paused and playing in full-screen mode. 

the attached screenshot is taken on step 3.  https://i.imgur.com/SoxEppT.jpg

Reproduced in firefox 62.0.2 and chrome 69.0.3497.100. 

live example : http://bit.ly/2DrEMbh (I don't if this is geo-blocked on not. probably it is).

suggestions welcome on how I can debug this. thanks.

**Comment by dilburt** [comment] 2018-10-02 02:15
I'm pretty sure you are running into the issue regarding the browser changes preventing unmuted autoplay and fullscreen without proper user interactions.

**Comment by Kiro705** [comment] 2019-10-23 21:10
Hi @Snowbell92 ,

Taking a look at the issue, but I am unable to reproduce. If it is still happening please reopen this issue and let me know specifics about the autoplay and mute settings for the video.

I will be closing this issue for now.

**Closed by Kiro705** 2019-10-23 21:10 UTC
