### ISSUE TITLE
Plugin Disables Big Play Button, Control Bar Looks Broken During Ad

### ISSUE THREAD

**Issue by casbboy** [googleads/videojs-ima#403] opened 2017-08-04 05:25 UTC
I have setup this test page to run a sample pre-roll:

https://www.traileraddict.com/util/new-trailer-test.php?utm_source=se

When you open the page you will notice that you can't click the Big Play button for some reason. This only happens when the player.ima setup is done.

To see the next issue, open console and type: player.play()

Which shows how bad the control bar looks (broken) when running a pre-roll. When the ad/video completes the original control bar returns and is fine again.

Any way to have the player work as it should before play and during ad?

Cheers!
Ryan

**Comment by shawnbuso** [comment] 2017-08-10 19:03
Hi there,

Did you change that test page? I took a look and the play button is working, but it looks like all the IMA plugin code has been commented out (unless I'm looking at the wrong source).

Thanks,
Shawn

**Comment by casbboy** [comment] 2017-08-10 19:24
Hey Shawn, you are right, I used the MailOnline vast/vpaid instead as it was working, but it is no longer supported so I still am hoping to get this working.

Here is the page with videojs-ima back live:

https://github.com/googleads/videojs-ima/issues/403#issuecomment-321643894

Button breaks instantly, so use the console to start the player.

Thanks!

**Comment by shawnbuso** [comment] 2017-08-10 19:29
Thanks for the link - it looks like you're using Video.js 5.19.2. Currently we only support up to 5.3 - could you check if it's working with that version of video.js? Thanks!

**Comment by casbboy** [comment] 2017-08-10 19:36
Sure, I changed it to 5.3 but seeing same errors: https://www.traileraddict.com/util/new-trailer-test2.php?utm_source=se

**Comment by shawnbuso** [comment] 2017-08-11 17:00
Sorry, I typed this up yesterday and sent it as a response to a different issue (:

Ah ok, it looks like you're seeing the same issue as #353 - we're having issues with the play button being disabled when preload is used. That user posted a workaround in that thread which involves waiting until the user clicks play to play ads. The issue is that the ad container is rendering above the play button and stealing its clicks. You can also try removing the z-index parameter from the ad container's stylesheet until the ad starts, and then re-adding it when the ad is playing.

As for the second issue, it looks like you have a different version of the Video.js stylesheet than we're using here. The one we use defines a font family called VideoJS, which is where we get the UI icons from. Your CSS seems to be missing that. Could you try using [this stylesheet](https://github.com/googleads/videojs-ima/blob/master/examples/simple/index.html#L20) instead to see if that works?

**Comment by casbboy** [comment] 2017-08-11 22:46
Thanks, I'll take a look. Yeah, I don't like preload, but my resolution picker requires it.

**Comment by casbboy** [comment] 2017-08-12 19:19
Hey Shawn,

Okay, i can see that I should be able to adjust z-index using events, but your documentation does not give any sense of events available with this plugin:

https://github.com/googleads/videojs-ima/wiki/API-Docs

That pages doesn't exist. lPossible to point to page for events. I can update the z-index on ad skip and or ad complete (and player start), but not sure which events to call. You have a page showing all events with this plugin?

Cheers
Ryan

**Comment by shawnbuso** [comment] 2017-08-21 04:51
Our docs are currently here -> https://github.com/googleads/videojs-ima/blob/master/docs/api/this.md

The plugin doesn't throw any events of its own, so there aren't any listed there - all the events you're using would be thrown either by the video player or the IMA SDK itself.

**Comment by ypavlotsky** [comment] 2018-01-02 21:06
Closing this as there hasn't been any activity in a while. If this is still an issue, feel free to let me know.

**Closed by ypavlotsky** 2018-01-02 21:06 UTC
Labels: support
