### ISSUE TITLE
Question re: setting source directly rather than using `setContentWithAdTag`

### ISSUE THREAD

**Issue by opinxit** [googleads/videojs-ima#735] opened 2018-09-10 15:09 UTC
We are using videojs-ima in conjunction with videojs-contrib-hls and playlists. We found when we move through the playlist items, if we use the `setContentWithAdTag` a race condition could cause the player to freeze if the ad started playing before the content loaded. The workaround we're auditioning is to change the source via `video.src`, and then once the `loadedmetadata` event is received by the player to set the adTag directly with `changeAdTag`.

The documentation for `setContentWithAdTag` states that: "You should use this method instead of setting the content src directly to ensure the proper ad tag is requested when the video content is loaded."

Is there something we should be aware of going forward if we use this approach? -- is there something going on behind the scenes that `setContentWithAdTag` takes care of that we should know?

**Comment by chris-feldman** [comment] 2018-09-13 19:29
I don't think setContentWithAdTag is doing anything special that should make your workaround insufficient.

The setContentWithAdTag function looks like the following:
```
Controller.prototype.setContentWithAdTag =
    function(contentSrc, adTag, playOnLoad) {
  this.reset();
  this.settings.adTagUrl = adTag ? adTag : this.settings.adTagUrl;
  this.playerWrapper.changeSource(contentSrc, playOnLoad);
};
```
The reset function eventually leads to the reset method in SdkImpl. From an IMA perspective, this function is destroying the adsManager and calling contentComplete on the adsLoader. This resets the SDK components and also forces IMA to use a different correlator for subsequent ad requests.

After the reset, the ad tag is updated in the settings (to be used by the upcoming ad request), and changeSource is called which updates the content source, but does not alter any IMA settings, as far as I can tell.

The changeAdTag method is very similar to setContentWithAdTag:
```
Controller.prototype.changeAdTag = function(adTag) {
  this.reset();
  this.settings.adTagUrl = adTag;
};
```

This means that the correlator will still be updated, and the tag will be changed for future ad requests. If the video source is correct after the manual update and the correct ad tag is being requested, I don't see any reason that the workaround would cause issues.

**Comment by ypavlotsky** [comment] 2018-09-13 19:31
Hi,

`setContentWithAdTag` handles the case of having existing content in the `video.src` nicely, but otherwise, your workaround seems OK if you're just using it for prerolls.

**Comment by opinxit** [comment] 2018-09-20 17:08
Thank you for the replies!

**Comment by grobolom** [comment] 2018-09-24 14:56
@minasaywhat 

1. Given that the race condition workaround would reverse the order that the current plugin works, I suspect it would make more sense to live in the custom player implementation. If you trace the calls here down, you'll see that this plugin adds a handler to `loadedmetadata` that handles calling the content start automatically.

2. It's likely you wouldn't need to work around this for post/mid/VMAP, as those won't run into the same race condition.

**Comment by Kiro705** [comment] 2019-10-23 15:49
Hi all,

I am planning to close this issue because the work around has been established as an acceptable implementation for this specific use-case.

If you have farther questions please feel free to reopen the issue.

I would like to ask how this specific playlist differs from our [playlist example](https://github.com/googleads/videojs-ima/blob/master/examples/playlist/ads.js), or if this race condition is reproducible in our samples.

**Closed by Kiro705** 2019-10-23 15:49 UTC

**Comment by opinxit** [comment] 2019-10-23 16:37
we found that with the release of this PR (https://github.com/googleads/videojs-ima/pull/800), we were able to reintroduce `setContentWithAdTag` with no ill effects. if your playlist example did not have the faulty `adDisplayContainer` initialization it may have flown under the radar.
