### ISSUE TITLE
Ad freezes in Safari after start

### ISSUE THREAD

**Issue by Nks** [googleads/videojs-ima#428] opened 2017-10-04 17:55 UTC
In chrome and Mozilla it works perfectly.
In Safari when I trying to start an advert it freezes on 0 second in safari and nothing else happens. To start playing advert I need click on "Pause" button and "Play" button again.

Safari version 11.0 (12604.1.38.1.7)
"video.js": "^5.20.3",
"videojs-ima": "^0.6.0"

As the video I'm using a mp4 file.

I tried to reproduce this problem in the examples and have same result.

[Here](https://www.youtube.com/watch?v=IBcu0LmAvpY&feature=youtu.be) I reproduced this issue.

Code which I using:

```
exports.imaAdPlayer = function (id) {
    this.id = id;
    this.init = function (autoPlay) {


        var player = videojs(this.id);

        if (typeof window.imaTagUrl === 'undefined') {
            console.debug('[ima] Tag URL is not set');
            return player;
        }

        console.log(window.imaTagUrl);

        var options = {
            debug: true,
            // timeout: 10000,
            // prerollTimeout: 1000,
            id: id,
            adTagUrl: window.imaTagUrl,
        };

        player.ima(options);

        player.one('ready', function () {
            player.ima.initializeAdDisplayContainer();
            player.ima.requestAds();
        });

        var contentPlayer = document.getElementById(id + '_html5_api');
        if ((navigator.userAgent.match(/iPad/i) ||
            navigator.userAgent.match(/Android/i)) &&
            contentPlayer.hasAttribute('controls')) {
            contentPlayer.removeAttribute('controls');
        }

        var startEvent = 'click';
        if (navigator.userAgent.match(/iPhone/i) ||
            navigator.userAgent.match(/iPad/i) ||
            navigator.userAgent.match(/Android/i)) {
            startEvent = 'touchend';
        }

        if (typeof autoPlay !== 'undefined' && autoPlay) {
            console.debug('[ima] autoplay');
            player.ima.initializeAdDisplayContainer();
            player.ima.requestAds();
        } else {
            player.one(startEvent, function () {
                console.debug('[ima] default video');
                player.ima.initializeAdDisplayContainer();
                player.ima.requestAds();
                player.play();
            });
        }

        return player;
    }
};
```

**Comment by shawnbuso** [comment] 2017-10-04 18:09
Hi there - this is a known issue with the IMA SDK in Safari 11. It will be fixed with the next release of the IMA SDK, and the plugin will pick that up automatically.

**Comment by Nks** [comment] 2017-10-04 18:15
@shawnbuso thanks for the answer! I hope this will be fixed soon :)

**Comment by sgromkov** [comment] 2017-10-05 05:10
I have the same issue. Waiting for update.

**Comment by sgromkov** [comment] 2017-10-05 05:12
@Nks Did you try to se vpaidMode to `INSECURE`? When I set it the ad is playing, but vpaid has no sound.

**Comment by KevinBrogan** [comment] 2017-10-10 21:52
I can give you a quick fix that might work....  it worked for me

```
function forcemuted(e){e.target.muted = true;}
videoElement.addEventListener('volumechange',forceMuted);
```

This will force the mute state of the video element to always be true. I was getting an errant muted = false from somewhere in the mess that is all of videojs, videojs ima, and the ima sdk. I couldn't figure out where it was coming from cause it only happens on ios and safari's stack traces are not asynchronous friendly.

Once you have the ad playing, it's up to you to find out when you want to disable the event listener. I used an event handler on the mutediv to do this in my implementation.

**Comment by sgromkov** [comment] 2017-10-24 12:40
@shawnbuso I saw the IMA SDK fix in 3.182.0 version: https://developers.google.com/interactive-media-ads/docs/sdks/html5/v3/history

The freeze problem is solved?

**Comment by shawnbuso** [comment] 2017-10-25 18:45
Yes click to play should be working on Safari 11 desktop. Autoplay isn't working yet - that may have to be a change in the plugin itself. We've been working on a refactor of the plugin, so that issue will be fixed either after or as part of the refactor.

**Comment by mrmckeb** [comment] 2017-10-30 05:18
@shawnbuso What's the ETA on that fix / refactor? This is hitting us in production unfortunately (we may look to disable autoplay).

**Comment by shawnbuso** [comment] 2017-10-30 15:28
Unfortunately I don't have an ETA right now. Autoplay on Safari has gotten very complicated with the update to Safari 11. Safari 11 now handles autoplay on desktop the same way they handle it on mobile web - it's disabled unless your video is muted. Our autoplay sample *does* mute the video, and works fine on mobile, but for some reason Safari 11 on Desktop still prevents it from autoplaying (this is not the first time we've seen confusing behavior like this with Safari 11). Unmuted autoplay will never work on Safari 11 because they explicitly forbid it as of version 11. Ideally we'll have a muted autoplay solution that works, and the ability to fallback to click-to-play if you want to attempt to play unmuted and get denied.

The latter is more complicated and may require us to loop in some video.js and contrib-ads folks. The issue is that browsers don't provide any API for you to check whether autoplay is supported or not - you just have to try to play your video, and if it fails, fall back to click to play. We could do this in the plugin, but ideally this would be handled by the video.js player.

**Comment by EugeneLyzo** [comment] 2017-11-15 10:33
Is it fixed now?

**Comment by shawnbuso** [comment] 2017-11-15 14:45
No update yet - the refactor mentioned above is still in progress.

**Comment by shawnbuso** [comment] 2018-01-19 16:23
Hi all - the refactor is now complete. Do you still see this issue if you update to a version >= 1.0?

**Comment by shawnbuso** [comment] 2018-01-24 15:34
I tested our samples on Safari with the latest version of the plugin and they are working, so I'm going to close this issue. If you're still seeing the issue with the new plugin feel free to re-open or start a new issue. Thanks!

**Closed by shawnbuso** 2018-01-24 15:34 UTC
Labels: IMA issue, P1

**Comment by mizmaar3** [comment] 2018-02-12 10:30
@shawnbuso Does this fix means if VPAID tag will try to autoplay video with sound on the plugin will force muted=true and then will play the video so video doesn't looks freeze on 1st frame ?

**Comment by shawnbuso** [comment] 2018-02-12 14:55
The plugin never forces any muted state - we just go with what you've set on the player. If a VPAID ad wants to auto-play, it's up to the author of the ad to sync it's volume with the volume of the content player on start.

**Comment by KevinBrogan** [comment] 2018-02-23 20:14
In otherwords, you allow the third party ad content to override the volume and mute settings, allowing bad providers to hijack the user's exerpience.

**Comment by shawnbuso** [comment] 2018-02-23 20:19
VPAID ads by design can create their own video player and do what they want with it. We can request that they start that player muted if the content is muted, but they have the ability to simply ignore that request if they wish.

**Comment by DurgaGangisetty** [comment] 2024-01-09 10:49
I am facing ads freezing issue when trying to play in Mac Machines

**Comment by Kiro705** [comment] 2024-01-09 14:53
Hello @DurgaGangisetty ,

I may recommend opening a new issues, since this one is over 5 years old. In addition, please include steps with how to reproduce the issue.

Thank you,
Jackson
IMA SDK team
