### ISSUE TITLE
Problem with Windows Chrome

### ISSUE THREAD

**Issue by ibraalek10** [googleads/videojs-ima#606] opened 2018-05-09 08:36 UTC
Hi all,
i have a problem with Google IMA Plugin in Windows Chrome..
When the page shows the player with ads and I use the mouseOver on video, the player blocks itself..
In console appears this warning: "**Unmuting failed and the element was paused instead because the user didn't interact with the document before**"..
I have set the "muted" and "playsinline" attributes and the problem is only on Windows Chrome..
I wait your answers,
Thanks a lot,

A.

**Comment by shawnbuso** [comment] 2018-05-09 17:11
Do you have a sample page where I can reproduce this myself? Thanks!

**Comment by ibraalek10** [comment] 2018-05-11 08:28
Hi @shawnbuso ,
in fact, when there is a mouseOver event, my player actives the sound of video..
The strange thing is that i have this problem only on Windows OS.. With MAC OS i don't have any problems on mouseOver event.. 
Is there a workaround for bypassing this problem???
I wait your answer,
Thanks a lot,

A.

**Comment by ibraalek10** [comment] 2018-05-14 09:48
HI @shawnbuso ,
in list of origin doesn't appears the test page that give me "problem"..
what do you suggest me?
Thanks a lot,

A.

**Comment by shawnbuso** [comment] 2018-05-14 18:25
Hmm that's odd, it should be there - you're not seeing it on either platform?

**Comment by ibraalek10** [comment] 2018-05-15 09:12
Hi @shawnbuso ,
I find it!!!
This is a screen of my "chrome://media-engagement/"

![schermata 2018-05-15 alle 11 10 05](https://user-images.githubusercontent.com/23355148/40047830-dae8376a-5830-11e8-90de-776d66aee5cf.png)

A.

**Comment by shawnbuso** [comment] 2018-05-15 14:43
Is this for your Windows machine or the Mac? The "No" value for "Is High" should mean that autoplay is not allowed for that domain for whatever platform you're on. If I had to guess I would say that this is your Windows machine, and that if you check on the Mac you'll see a "Yes" value for "Is High" for your test domain(s).

**Comment by ibraalek10** [comment] 2018-05-15 14:50
Hi @shawnbuso,
this screenshot is for my MAC..
Now, I have done a check on my Windows machine and the result is the same for "Is High" parameter..

A.

**Comment by shawnbuso** [comment] 2018-05-15 14:59
Hmm odd - it could just be then that Windows and Mac Chrome handle mouse movement differently, and one considers it a user action while the other does not. I can do some testing and research and let you know what I find.

**Comment by janhjordie** [comment] 2018-08-01 13:38
Did one of you @shawnbuso or @ibraalek10 found a solution on this ?
I'm actually having exact same issue on a ad engine one of our my customers has build

When you scroll below the smoothie a video pops up ! But because of the media index is to low, the unmute fails

https://gastromand.dk/weber-pulse-2000-brunchpizza-paa-grill/?google_preview=i05cpSCjcZcY35Xu2QUw37Gj4QWIAYCAgKCbsYeutQE&iu=5706918&gdfp_req=1&lineItemId=4473143011&creativeId=138237879722

**Comment by Kiro705** [comment] 2019-10-15 19:57
Hi all,

It looks like this is not an issue, but instead expected behavior for autoplaying videos with sound. 

At the time of this post both safari and chrome do not consider a mouseover user interaction and will not unmute an autoplaying video. Here is the [chrome guide on autoplaying](https://developers.google.com/web/updates/2017/09/autoplay-policy-changes).

As a note, a mouseover does work to unmute in firefox.

To handle autoplaying across multiple browsers, please take a look at our [autoplaying guide](https://github.com/googleads/videojs-ima/tree/master/examples/autoplay).

I will be closing this issue, but please feel free to reopen if this does not address your issue.

**Closed by Kiro705** 2019-10-15 19:57 UTC
Labels: support
