### ISSUE TITLE
hiding controls not working on all ads

### ISSUE THREAD

**Issue by yanfaingold** [googleads/videojs-ima#756] opened 2018-10-11 14:37 UTC
i found this issue https://github.com/googleads/videojs-ima/issues/477 but the option mentioned there never been added right?

**Comment by ypavlotsky** [comment] 2019-01-08 19:45
It hasn't been added.

**Comment by canhnm** [comment] 2019-02-11 08:10
Walk around trick:
Adding css:
```
.ima-controls-div {
  display: none !important;
}
```

**Comment by Kiro705** [comment] 2019-10-30 16:47
Hi @aFilipMalinowski ,

Thanks for the feedback, I will look into adding this feature.

**Comment by Kiro705** [comment] 2020-02-27 17:00
Hello, looking into this issue again.

To clarify, the issue is not having the ability to hide / show ad controls through JS?

Or is the goal to simply not have any ad controls. (Certain controls like the skip ad and Learn More on small screens are built into the SDK  and cannot be removed.)

**Comment by aFilipMalinowski** [comment] 2020-03-02 09:16
Sorry. Was not in the office past few days and didn't have an opportunity to respond.

> To clarify, the issue is not having the ability to hide / show ad controls through JS?
Yes.

> Certain controls like the skip ad and Learn More on small screens are built into the SDK and cannot be removed.
This is fine. Only being able to hide playback controls except for the ones which are built into the SDK is what we would love to have.

**Comment by Kiro705** [comment] 2020-03-03 15:29
Hi @aFilipMalinowski ,

I am adding a setting to disable ad controls in pr #896 

Once it is merged I will close this issue, but let me know if you think there are any changes that need to be made.

**Closed** 2020-03-03 18:48 UTC
Labels: P2, enhancement
