### ISSUE TITLE
Videojs controller killed by Overlay ads

### ISSUE THREAD

**Issue by morgo77** [googleads/videojs-ima#427] opened 2017-10-03 13:24 UTC
Hello,

I'm using videojs with captions and resolution picker like this:
<video id="video" class="video-js vjs-default-skin vjs-big-play-centered" controls preload="auto" width="300" height="169">
<source src='http...' type='video/mp4' label='low'/>
<source src='http...' type='video/mp4' label='medium'/>
<track kind='captions' src='http...' srclang='en' label='Default' default>
</video>

When I get Overlay ads I can't access the videosjs controlls anymore like subtitle options.
If I set **visible=false** to **div id=video_ima-ad-container** that the extra layer disappears and the controlls will be works again. In case of preroll videos it works well after the advertisement only the Overlay banners got this issue.

Chrome marked video_ima-ad-container with blue
<img src="https://i.imgur.com/4UkwnLRl.png">

Caption's options seems like this, but only, subtitle button can be clicked, due the other layer
<img src="https://i.imgur.com/bMPFyZD.png">

I've seen this issue on youtube as well.
Do you have any idea how to fix this?

**Comment by shawnbuso** [comment] 2017-10-03 16:37
Are you having the same issue accessing controls if you plug your tag into our [advanced example](http://googleads.github.io/videojs-ima/examples/advanced/)? If so, could you share your tag so I can take a look with your ad(s)? If I plug our [sample nonlinear tag](https://pubads.g.doubleclick.net/gampad/ads?sz=480x70&iu=/124319096/external/single_ad_samples&ciu_szs=300x250&impl=s&gdfp_req=1&env=vp&output=vast&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ct%3Dnonlinear&correlator=&debug_experiment_id=1269069638) into that player it works ok (I don't have CC but I can still interact with play/pause, mute, etc.) so it may be an issue specific to your ad. Thanks!

**Comment by morgo77** [comment] 2017-10-05 08:01
I just moved here a sample
Sometimes it gives preroll instead of overlay ads just hit F5.
Play/pause etc buttons works fine but vjs-menu items can't be clicked when overlay ads was shown.
http://szarwp.we2host.lt/player/

**Comment by shawnbuso** [comment] 2017-10-05 14:40
Thanks for the sample - it looks like this is an issue with the ad container filling the whole video display even when the ad is non-linear. I'll need to look into this a bit more. We can try to resize the ad container to be the size of the ad, but that may mess with ad rendering, so it will require a bit of work.

**Comment by morgo77** [comment] 2017-10-05 19:16
Thanks for the analisys. :)
It can be a solution when a.close-button fired/or the timer minimize the ad
than div id=video_ima-ad-container could get a visible=false style element?

**Comment by shawnbuso** [comment] 2018-01-19 16:22
Hi there - I wanted to revisit this one but it looks like the sample page has gone down. Do you have another I could take a look at? Thanks!

**Comment by canhnm** [comment] 2018-01-31 02:43
Hi @shawnbuso  I am currently facing issue with nonlinear overlay ad, videojs-ima return 501 error: Ad error: AdError 501: The overlay ad content could not be displayed since creative dimensions do not align with display area.

Woul you like to have a look? I will send you the test link!

**Comment by shawnbuso** [comment] 2018-01-31 17:36
Can you send me a sample page where I can reproduce this? Thanks!

**Comment by shawnbuso** [comment] 2018-02-07 19:45
Closing this out since we haven't had a response to the initial issue for ~3 weeks. If you're still seeing this problem please feel free to re-open this issue or open a new issue. Thanks!

**Closed by shawnbuso** 2018-02-07 19:45 UTC
Labels: P2, bug
