### ISSUE TITLE
Microsoft Edge waterfall breaking on CORS

### ISSUE THREAD

**Issue by Slind14** [googleads/videojs-ima#647] opened 2018-06-10 02:44 UTC
Hi there,
when using Edge, the waterfall is stopping when a CORS happens. .e.g.:
`SEC7120: [CORS] Der Ursprung "https://imasdk.googleapis.com" konnte "null" im Access-Control-Allow-Origin response header für die cross-origin -Ressource bei "https://cm.g.doubleclick.net/pixel?google_nid=contextweb&google_cm&google_sc" nicht finden.`

In other browsers e.g. Chrome, Firefox I do not even encounter the CORS on all google tags like it is with Edge. Though when there is a CORS (very rarely) it doesn't break the waterfall.

**Comment by Slind14** [comment] 2018-06-11 03:34
There is also the issue of this error which I'm only getting in Firefox:
![image](https://user-images.githubusercontent.com/3914677/41211667-11e2f634-6d39-11e8-8fdd-d7e21f0fe9fa.png)

**Comment by shawnbuso** [comment] 2018-06-12 14:01
Hey there,

Do you have a sample page where I can reproduce these issues? If you don't have a page you can share, could you share your ad tag?

Thanks,
Shawn

**Comment by Slind14** [comment] 2018-06-16 12:30
I posted the implementation here: https://github.com/googleads/videojs-ima/issues/649

**Comment by Kiro705** [comment] 2019-10-16 14:40
Closing this issue due to being a duplicate of https://github.com/googleads/videojs-ima/issues/649

**Closed by Kiro705** 2019-10-16 14:40 UTC
