### ISSUE TITLE
`ended` event does not fire first time after an ad

### ISSUE THREAD

**Issue by longlivelance** [googleads/videojs-ima#600] opened 2018-04-25 17:29 UTC
We have discovered an issue where the `ended` event does not fire the first time a video ends after an ad is played. Currently, if an ad plays, and the video finishes, the `ended` event is not fired. If you then rewind a few seconds and hit play, this time, when the video finishes, an `ended` even is fired. 

If the ima plugin is not initialized, the `ended` events fire as expected on video end the first time.

There are no errors listed in the console. If there is additional information that would be useful, please let me know.

VideoJS version 6.7.3
IMA Plugin version 1.3.0
VideoJS Contrib Ads version 6.0.0

**Comment by longlivelance** [comment] 2018-04-26 16:53
FWIW, I noticed this fix for issue #559  in the 1.3.0 release notes, so thought I would give `contentended` a try. The `contentended` event fires without any trouble at the end of the video. That works for my situation as well, so I will use it.

I also noticed that using the dev tools Event Listener Breakpoints on the ended event pauses execution on the event. However, the event is not fired on the actual player until you rewind and it is fired a second time. Also worth noting is that after doing so, the player seems kind of in an odd state. For example, loading a new source and playing it is stalled for a few seconds before it seems to actually take. With the IMA plugin disabled, this behavior is not noticed.

**Comment by ypavlotsky** [comment] 2018-04-27 17:49
We are still using the 6.0 release of contrib-ads. Do you find the issue goes away after upgrading to a new contrib-ads?

**Comment by longlivelance** [comment] 2018-04-28 01:41
After upgrading to contrib-ads 6.2.0, and pointing to that version from the integration, the issue went away. So I would say the bug was i the ads plugin rather then the ima plugin.

**Comment by ypavlotsky** [comment] 2018-04-30 13:41
Thanks for the info. I think we'll put in a change to contrib-ads 6.2.0 as soon as we can.

**Comment by Kiro705** [comment] 2019-10-15 17:51
Closing the issue. It looks like it was discovered to be an issue with the contrib-ads plugin and not the videojs-ima plugin

**Closed by Kiro705** 2019-10-15 17:51 UTC
Labels: enhancement

**Comment by justinbeatz** [comment] 2023-12-26 14:43
> We have discovered an issue where the `ended` event does not fire the first time a video ends after an ad is played. Currently, if an ad plays, and the video finishes, the `ended` event is not fired. If you then rewind a few seconds and hit play, this time, when the video finishes, an `ended` even is fired.
> 
> If the ima plugin is not initialized, the `ended` events fire as expected on video end the first time.
> 
> There are no errors listed in the console. If there is additional information that would be useful, please let me know.
> 
> VideoJS version 6.7.3 IMA Plugin version 1.3.0 VideoJS Contrib Ads version 6.0.0

Sadly, this is still happening with the latest version of VideoJS 8, Contrib Ads 7.3.2, VideoJS IMA 2.2.0 and VideoJS Playlist 5.1.0.

**Comment by Kiro705** [comment] 2023-12-27 18:18
Hello @justinbeatz ,

When testing for the following events, I see both events fire when a post-roll is loaded and played. `'contentended'` fires when the content video ends, and `'ended'` fires when the post-roll finishes. Could you share any additional steps needed to reproduce the issue, and please reopen the issue as needed.

These are the events I set up:

```
player.on('contentended')
player.on('ended')
```

Thank you,
Jackson
IMA SDK team

**Comment by Daghall** [comment] 2025-08-13 09:43
FYI, the `contentended` event has been deprecated.

The recommendation is to replace it with `readyforpostroll`, [according to the `videojs-contrib-ads` docs](https://videojs.github.io/videojs-contrib-ads/integrator/api.html).
