### ISSUE TITLE
Player freezing after ad

### ISSUE THREAD

**Issue by Slind14** [googleads/videojs-ima#679] opened 2018-06-28 04:12 UTC
Hi there,
there is an ad from AdX which is freezing the player once it ends.
Ad Id: "d59884ee-1445-4d8e-b66e-d39e7bcdcb25"
Ad Query Id: "307699625"
Media URL: "https://s1.adform.net/banners/scripts/video/VPAIDWrapper.min.js?cache=14"

Can the freeze be prevented?

![image](https://user-images.githubusercontent.com/3914677/42012804-4bd94500-7a9a-11e8-8282-ea910e60afa6.png)

**Comment by Slind14** [comment] 2018-07-02 09:52
Just wanted to check in. Is the provided ad and ad query id enough to track down the issue?

**Comment by ypavlotsky** [comment] 2018-07-03 14:07
Hi there,

We can't troubleshoot any serving issues with your AdX ad. Do you have an example page where the freeze happens?

**Comment by Slind14** [comment] 2018-07-03 14:23
It is only this AdX ad that is freezing the player. Other players are not freezing when this ad plays. how would you go about debugging it if it is only available programatically?

**Comment by ypavlotsky** [comment] 2018-07-03 14:31
Are you getting a javascript error when the freeze happens? You can try a proxy to log all the requests and responses to see if anything strange is happening there. Otherwise I would recommend checking in the the DFP support forums which handles AdX: https://productforums.google.com/forum/#!forum/dfp

**Comment by Slind14** [comment] 2018-07-03 14:41
It's not throwing any errors. 
The other players (where it is working fine) are using the ima sdk as well, how can the DFP support help in this case?

**Comment by ypavlotsky** [comment] 2018-07-03 14:48
If it's an issue with the ad, which appears to be a VPAID, you can ask DFP support. It could also be an issue with the player. You can try other VPAID ads, like this [sample](https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/single_ad_samples&ciu_szs=300x250&impl=s&gdfp_req=1&env=vp&output=vast&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ct%3Dlinearvpaid2js&correlator=) to see if your player plays VPAID normally.

**Comment by damianvila** [comment] 2019-03-15 13:13
Hello,
We are seeing a similar effect, when a pre-roll is played over a streaming content, the `Preroll -> ContentPlayback` event is never fired.
I've checked, and found that, while `PlayerWrapper.prototype.onAdBreakStart` has a `this.vjsPlayer.pause();`, `PlayerWrapper.prototype.onAdBreakEnd` doesn't have a corresponding `this.vjsPlayer.play();`, so adding it solves this issue.
Check if this is your case.

**Comment by Kiro705** [comment] 2019-10-18 15:38
Hi all,

Looking into this it looks like an issue with the ad-tag. 

@damianvila work around presents a potential issue.

`PlayerWrapper.prototype.onAdBreakEnd = function() {
  this.vjsPlayer.on('contentended', this.boundContentEndedListener);
  if (this.vjsPlayer.ads.inAdBreak()) {
    this.vjsPlayer.ads.endLinearAdMode();
  }
  this.vjsControls.show();
};`

The call to `this.vjsPlayer.ads.endLinearAdMode();` should restart the player, but it is only called if `this.vjsPlayer.ads.inAdBreak()` evaluates true.

I think that the issue might be that related to `this.vjsPlayer.ads.inAdBreak()` evaluating false. I am going to look into replacing that to `this.vjsPlayer.ads._inLinearAdMode` because that seems more related to then calling `this.vjsPlayer.ads.endLinearAdMode();`

I will follow up on this issue soon.

**Comment by Kiro705** [comment] 2019-10-18 17:58
Hey all,

Take a look at this pr https://github.com/googleads/videojs-ima/pull/840

I think the change might be able to solve the issue, but because I am not able to reproduce, I cannot confirm that.

Let me know if it works for you.

**Comment by broadcoder** [comment] 2019-10-24 13:49
Hey there, I'm not convinced this will fix the issue. I am currently trying to implement ad breaks aswell and the problem is related to some misbehavior of the ima plugin according the contract between this ad-plugin and videojs-contrib-ads.

First of all, I'm pretty sure the problem in this issue happens because the media ressource is a live stream. And as far as I have seen, there were other issues about playing live streams with video js and the ima plugin. It just can't deal with live streams and I dug really deep into the ima and the contrib-ads plugin to figure out, what is happening.

I have already seen shawnbuso mention the problem here in #629 in May 2018 and it seems to be still not fixed. Based on what shawnbuso said, it's pretty obvious, that the ima plugin doesn't stick to the contrib-ads plugin contract. If the content is a Live-Stream, it should not be paused, since contrib-ads will expect the media ressource to keep running, mutes it and hide it by adding the `vjs-ad-playing` class. Since ima pauses the content player no matter if it's live or not, it won't get resumed automatically by contrib-ads, because all it does is removing the class again and unmute the content player.

It's even worse, the contrib-ad plugin does not store a snapshot of the content player, if the content is live, and thus won't restore the content player when the ad ends even if you would fix the freeze issue by calling play in `PlayerWrapper.prototype.onAdBreakEnd`. This would cause the stream to start from the beginning after an ad break and is not the correct behavior.

I think the problem is, that this plugin was never ment to work with live streams, but it definitly should do. A simple fix for this issue would be to introduce the new option `liveContent`, which default to false to not break anything, but wrap the hard vjsPlayer.pause() call in an if statement to not pause if the option is set to true. Of course it would be great, if you could detect dynamically if the content is Live, but this simple option would be enough as a quick fix.

**Comment by Kiro705** [comment] 2019-10-25 14:35
Hi @broadcoder ,
Thanks for the update.

I see, if this is related to https://github.com/googleads/videojs-ima/issues/629 it looks like it may require the cuePoints feature to be implemented into the videojs-ima plugin.

I will continue to investigate the issue and the potential of adding that feature.

**Comment by malini** [comment] 2020-02-05 17:49
@Kiro705 Hi, is there an ETA for a fix for this? I'd like to use this for live playback.

**Comment by Kiro705** [comment] 2020-02-05 22:06
Hi @malini ,

This feature has not yet been prioritized, so there is no ETA available.

**Comment by oleksiiha** [comment] 2020-02-26 16:38
Workaround that worked for me is this:
```
playerInstance.on('adend', () => playerInstance.play())
```

**Comment by Kiro705** [comment] 2020-02-27 16:51
Hi all,

Looking into this issue, I am having a tough time reproducing the issue. Could someone share how they are able to reproduce it? (sample content and sample AdX ad)

**Closed** 2020-09-25 14:26 UTC
Labels: support

**Comment by dj4385** [comment] 2022-01-07 12:52
> Are you getting a javascript error when the freeze happens? You can try a proxy to log all the requests and responses to see if anything strange is happening there. Otherwise I would recommend checking in the the DFP support forums which handles AdX: https://productforums.google.com/forum/#!forum/dfp
![Screenshot from 2022-01-07 18-19-07](https://user-images.githubusercontent.com/30724457/148546571-bd86e026-eaf9-481e-a8ea-162656639f53.png)

**Comment by DurgaGangisetty** [comment] 2024-01-09 11:05
> Hi all,
> 
> Looking into this it looks like an issue with the ad-tag.
> 
> @damianvila 's work around presents a potential issue.
> 
> `PlayerWrapper.prototype.onAdBreakEnd = function() { this.vjsPlayer.on('contentended', this.boundContentEndedListener); if (this.vjsPlayer.ads.inAdBreak()) { this.vjsPlayer.ads.endLinearAdMode(); } this.vjsControls.show(); };`
> 
> The call to `this.vjsPlayer.ads.endLinearAdMode();` should restart the player, but it is only called if `this.vjsPlayer.ads.inAdBreak()` evaluates true.
> 
> I think that the issue might be that related to `this.vjsPlayer.ads.inAdBreak()` evaluating false because of something specific to the ad tag. I am going to look into replacing that to `this.vjsPlayer.ads._inLinearAdMode` because that seems more related to then calling `this.vjsPlayer.ads.endLinearAdMode();` and that might fix the issue
> 
> I will follow up on this issue soon.

But it is throwing  this.vjsPlayer.ads._inLinearAdMode is not a functionCan any one help me to resolve this
