### ISSUE TITLE
On iPhone, ad plays in background while content is paused full-screen

### ISSUE THREAD

**Issue by TablesawTablesawsen** [googleads/videojs-ima#317] opened 2016-12-09 04:40 UTC
I'm integrating the IMA plug-in into a somewhat elaborate VJS script, and I'm having trouble getting the iPhone integration to work. The placeholder before creating the player example isn't feasible with how our player is set up.

I've been trying different configurations with little success, but most result in:

1. the content video goes to full screen
2. the content video pauses
3. **the ad plays unseen in the background while the content video remains paused full-screen**
4. the content video resumes after the ad finishes playing.

I'm working on getting a good example of the problem for review, but if this suggests a solution for debugging, I would welcome some guidance.

**Comment by shawnbuso** [comment] 2016-12-09 14:43
Hi there,

Is your ultimate goal to have the video play in the fullscreen player or to play embedded in the web page?

Thanks,
Shawn

**Comment by TablesawTablesawsen** [comment] 2016-12-09 18:57
Ideally, we'd want both the video and the ad to play in the fullscreen player, but if they play embedded, we are okay with that for now.

**Comment by shawnbuso** [comment] 2016-12-12 16:21
OK thanks - it looks like right now IMA will always choose to play the ad embedded on iOS 10+. I'm working with the IMA SDK team to see if we can get it to sync with the content player so that either mode will work. If you do get an example together that I can use to debug let me know.

**Comment by TablesawTablesawsen** [comment] 2016-12-14 01:09
I've put a stripped down version of our player/ad integration with source maps at http://test.airmedia.com/testPlayer/ . Using this configuration, we do rarely see ads running correctly (ad runs inline then content plays), but it's not common. If we can get the ad to reliably play inline before  the content goes full-screen, that would be an acceptable outcome for us.

The package dependencies are:
```
{
  "dependencies": {
    "global": "^4.3.1",
    "video.js": "^5.12.6",
    "videojs-contrib-ads": "^3.1.2",
    "videojs-contrib-hls": "^3.4.0",
    "videojs-ima": "^0.5.0"
  },
  "browser": {
    "fakevjs": "./node_modules/video.js/es5/video.js",
    "videojs-ima": "./node_modules/videojs-ima/src/videojs.ima.js"
  },
  "browserify": {
    "transform": [
      "browserify-shim"
    ]
  },
  "browserify-shim": {
    "videojs-ima": {
      "depends": [
        "fakevjs:videojs"
      ]
    }
  }
}
```

**Comment by bamboocreative** [comment] 2017-01-16 15:41
@shawnbuso whats the status on this one? Experiencing the same issue here.

**Comment by shawnbuso** [comment] 2017-01-17 14:51
No update yet but I am working with the rest of the engineering team to get the fix prioritized.

**Comment by shawnbuso** [comment] 2017-01-17 20:38
Hi there,

As of yet I'm not able to reproduce this in our samples, only in the sample page that you sent us - could you point me to your source for the video player implementation so I can take a look at how you have the player and plugin set up?

Thanks,
Shawn

**Comment by TablesawTablesawsen** [comment] 2017-01-21 03:58
@shawnbuso I'm working on getting a sample with a suitable test tag. When I use the ad tag from your iphone sample (`http://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/ad_rule_samples&ciu_szs=300x250&ad_rule=1&impl=s&gdfp_req=1&env=vp&output=xml_vmap1&unviewed_position_start=1&cust_params=sample_ar%3Dpremidpostpod%26deployment%3Dgmf-js&cmsid=496&vid=short_onecue&correlator=`), the ad displays correctly, but when I use our LKQD test tag, it fails. (Though it's not _just_ the tag; the LKQD test tag works correctly on the iphone sample.)

I should be able to get you source and tag next week.

**Comment by A-Hadi786** [comment] 2017-01-24 11:09
@shawnbuso I am facing the same issue in Firefox mobile browser , the ad video goes to full screen and screen hangs when the ad is ended, while video content played in background.
In android default browsers play button on ad container does not respond on Tap or touchend.

Any solution ?

**Comment by shawnbuso** [comment] 2017-01-24 15:04
It sounds like this is the opposite problem to the one people are reporting here - folks here are saying the ad plays in the background while content plays full screen, while your problem is that the ad plays full screen then content plays in the background. Could you open a separate issue for this one so we can track it separately? Thanks!

**Comment by shawnbuso** [comment] 2017-02-09 17:16
I'm going to close this out since it's been ~20 days since @TablesawTablesawsen last responded, but if you still need assistance feel free to re-open. Thanks!

**Closed by shawnbuso** 2017-02-09 17:16 UTC
Labels: awaiting_response, support

**Comment by ryankevans** [comment] 2017-02-16 04:28
I worked with @TablesawTablesawsen to find a workaround for this issue, and I created a small test case which highlights the problematic behavior along with 2 functional workarounds:

Demo: https://ryankevans.github.io/videojs-ima-317/index.html
Repo: https://github.com/ryankevans/videojs-ima-317

The issue (fullscreen video content/player paused, obscuring the inline advertisement) does not occur every time, but it does occur on most attempts.
