### ISSUE TITLE
no iframe title on imasdk bridge iframe

### ISSUE THREAD

**Issue by spormeon** [googleads/videojs-ima#1129] opened 2023-12-11 13:06 UTC
Hi

Does videojs ima have any control ability to push a "title" for this iframe, as it throws errors in chrome lighthouse, which when this is a google repor, I'd of thought this would be sorted out, as your reporting on your own errors in effect?

![DevTools_-_127_0_0_1_5502_prebid_VideoDemo_DemoSite_pages_BBH_html](https://github.com/googleads/videojs-ima/assets/8503167/e5d0c5b3-299b-433d-be7d-e63e7aac7067)

**Comment by Kiro705** [comment] 2023-12-27 18:33
Hello @spormeon ,

The `<iframe>` you are referencing is created by the IMA SDK, not directly by the videoJS-IMA plugin. See the [VSI player](https://googleads.github.io/googleads-ima-html5/vsi/), which does not use the videoJS-IMA plugin.

If adding a title for the iframe is a requirement for you, I would recommend asking for a feature request on the [IMA technical forum](https://groups.google.com/g/ima-sdk), since this change will need to come on the IMA SDK side.

Please let me know if you have any other questions.

Thank you,
Jackson
IMA SDK team

**Comment by spormeon** [comment] 2023-12-27 19:09
Ok, I'll raise it over there.  What about this one, this constantly appears, I saw in one of the ima sdk releases, this is supposed to have been fixed in V3.598.0, which was actually yourself jackson:

![DevTools_-_cdn_adysis_com_VideoDemo_DemoSite_pages_playlistUIverticalAmazonParallelReBid_html](https://github.com/googleads/videojs-ima/assets/8503167/54ac5319-cd99-4f4f-bd10-1ecda62daa26)

**Comment by Kiro705** [comment] 2023-12-27 21:15
Hello @spormeon ,

Is this issue specific to the IMA videoJS plugin? Otherwise, you should raise the issue on the technical forum as well.

What do you mean that it was "actually yourself Jackson"?

If the issue does only occur with the videoJS plugin, it might make sense to create a new issue here, with steps to reproduce, since this issue is about the iframe issue you described eariler.

Thank you,
Jackson
IMA SDK team

**Comment by spormeon** [comment] 2023-12-27 21:17
you did ima sdk V3.598.0 release , according to the release threads

**Comment by Kiro705** [comment] 2023-12-27 21:31
I see, I was the one who documented the release of that version, correct. The IMA engineering team cuts those releases, but it is my team that documents those changes.

**Comment by spormeon** [comment] 2023-12-27 21:34
so the problem is on the page you mentioned above, i.e here: https://googleads.github.io/googleads-ima-html5/vsi/    its another cxase of google telling google , fix something

**Comment by Kiro705** [comment] 2023-12-27 22:18
The VSI player is not part of this GitHub repository. Closing this issue, but feel free to open a new issue in the correct location.

**Closed by Kiro705** 2023-12-27 22:18 UTC
Labels: enhancement, P2
