### ISSUE TITLE
Duplicate countdown on VAST without VPAID ads

### ISSUE THREAD

**Issue by cdatehortuab** [googleads/videojs-ima#855] opened 2019-10-28 19:29 UTC
Hello, this is related with bug #453

There are duplcate controls when you have the following conditions:

- `showControlsForJsAds` is set to `true`
- `adsRenderingSettings.useStyledLinearAds` is set to `true`
- A VAST without VPAID ad tag is loaded into the plugin (Example: [https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/single_ad_samples&ciu_szs=300x250&impl=s&gdfp_req=1&env=vp&output=vast&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ct%3Dskippablelinear&correlator=](https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/single_ad_samples&ciu_szs=300x250&impl=s&gdfp_req=1&env=vp&output=vast&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ct%3Dskippablelinear&correlator=))

Check the result here:

![Duplicate countdown](https://user-images.githubusercontent.com/8930653/67710549-269ce700-f98e-11e9-9287-73f9731e9b17.png)

I will submit a PR that will fix this.

**Comment by arnaudcasame** [comment] 2019-10-28 20:20
Hi,

It seems that the issue ticket [#453](https://github.com/googleads/videojs-ima/issues/453) was fixed with the PR [#836 ](https://github.com/googleads/videojs-ima/pull/836).

**Comment by cdatehortuab** [comment] 2019-10-28 20:21
@arnaudcasame  Read the description carefully. The causes in that bug were not corrected identified.

**Comment by Kiro705** [comment] 2019-10-28 20:44
Hi @cdatehortuab ,

I was working to reproduce your issue. In addition to setting `adsRenderingSettings.useStyledLinearAds` to true, are you calling `player.ima.setShowCountdown(true);`?

That was the only way I was able to get both countdowns to show.

**Comment by cdatehortuab** [comment] 2019-10-28 21:00
Oh yeah. I forgot about it.

**Comment by arnaudcasame** [comment] 2020-02-21 22:03
Hi,

I’m closing this issue because it has been inactive for more than a month. Please reopen if you still encounter this issue with the [latest stable version](https://github.com/googleads/videojs-ima/releases/tag/v1.7.4)

Thank you!

**Closed by arnaudcasame** 2020-02-21 22:03 UTC
