### ISSUE TITLE
videojs IMA SDK plugin & Vast 4.0 support

### ISSUE THREAD

**Issue by andscova** [googleads/videojs-ima#420] opened 2017-09-12 11:02 UTC
Hello,

some customers are starting to make use of VAST 4.0 functionalities (https://www.iab.com/guidelines/digital-video-ad-serving-template-vast-4-0/ ).

Is VAST 4.0 support on roadmap? If yes, could you provide a timeframe for its implementation on IMA SDK Plugin for Video.js?

Many thanks,

a.

**Comment by shawnbuso** [comment] 2017-09-14 17:36
Currently the IMA SDK supports VAST 4 at parity with VAST 3 - that is to say that if you take a VAST 3 response and change the version number to "4" it will work. We don't yet have support for the new VAST 4 features. Once the IMA SDK adds that support this plugin will pick it up automatically.

**Comment by mizmaar3** [comment] 2018-03-19 08:53
@shawnbuso Still no roadmap for VAST 4 support ?

**Comment by minasaywhat** [comment] 2018-08-14 19:29
Question - Can you shed any light on what (new 4.0) attributes we can look for in the VAST response that could cause issues in the IMA SDK + video.js, to help us in our troubleshooting process? It seems like some VAST 4.0 ads work in our player, so I'm trying to figure out what to look for to determine if issues are caused by the version incompatibility. Thanks in advance for your guidance.

**Comment by Kiro705** [comment] 2019-10-16 18:28
Hi all,

Our support of VAST 4.0 through the plugin is determined by the IMA SDK's support of VAST 4.0 .

If there are missing features please reach out through the [IMA SDK Google Group](https://groups.google.com/forum/#!forum/ima-sdk).

I am going to close the issue, but if you find VAST 4 features in the SDK not supported by the videojs-ima plugin please open an issue for the specific feature.

**Closed by Kiro705** 2019-10-16 18:28 UTC
Labels: IMA issue, P3
