### ISSUE TITLE
Ad not muted on Desktop when video is muted

### ISSUE THREAD

**Issue by stoicbuddha** [googleads/videojs-ima#444] opened 2017-10-31 21:06 UTC
This may be related to [#431](https://github.com/googleads/videojs-ima/issues/431), I'm not sure.

When a video is muted (the video tag itself has the `muted` property, and the player is muted via `player.muted(true)`) on desktop, the ad itself is not muted.

Muting works fine on mobile (iOS, Android).

Test here: http://staging.player.dotstudiopro.com/share/5888d13799f815762ffb077d?targetelm=.player&companykey=5888cfa099f815bd28fb077d&skin=228b22&debug=true&autostart=true

If I try to check the ad volume via `player.ima.getAdsManager().getVolume();`, it returns 0.  If I set the volume to 0 via `player.ima.getAdsManager().setVolume(0);`, it mutes and fires off the ad muted event in the console.

Browser: Chrome 61
OS: MacOS Sierra

**Comment by shawnbuso** [comment] 2017-11-01 14:13
Hmm this is odd - I don't think this is related to #431 because when I put your ad tag in our autoplay example, which starts muted, it does start muted. I'll check with the SDK team to see if there's something funny going on in the SDK here.

**Comment by stoicbuddha** [comment] 2017-12-08 22:28
Is there any update on this?

**Comment by shawnbuso** [comment] 2017-12-11 15:10
I think this will be resolved once #456 is submitted, but I can't say for sure because I was never able to reproduce it in my own code, only on your page. Also when I check that page now I see both the ads and content playing unmuted - was something changed there?

**Comment by stoicbuddha** [comment] 2017-12-11 16:48
I did work on it a little last night but nothing involving muting.  Wasn't there an IMA SDK update pushed the day after I reported this?

**Comment by shawnbuso** [comment] 2017-12-11 18:29
Cool, if you see the issue pop up again let me know and I will take a look. Thanks!

**Comment by stoicbuddha** [comment] 2017-12-22 21:36
This issue still exists using our player [here](http://staging.player.dotstudiopro.com/share/5888d13799f815762ffb077d?targetelm=.player&companykey=5888cfa099f815bd28fb077d&skin=228b22&debug=true&autostart=true&muteonstart=true).

**Comment by stoicbuddha** [comment] 2017-12-22 21:38
I'm also still able to get the player volume the same way as in the original post above and it says 0.  I can set it to 1, then to 0, and then it will be muted.  So it seems to think it's muted.

**Comment by stoicbuddha** [comment] 2017-12-29 21:56
Are there any updates on this?

**Comment by ypavlotsky** [comment] 2018-01-02 21:31
I'm seeing the ad muted on your sample page. This is in Chrome on Linux.

**Comment by stoicbuddha** [comment] 2018-01-02 21:33
@ypavlotsky Just today I managed to figure out a (hacky, imo) way to get the ads to mute.  On the ad loaded event, I use the ads manager to set the volume to 0 and this seems to do the trick.  Not exactly a good solution and the problem technically still exists.

**Comment by pankaj3960x** [comment] 2018-01-29 12:49
@stoicbuddha removing these particular options from plugin initialization does the trick for me

{
       disableFlashAds: true,
      adsRenderingSettings: {
        enablePreloading: true
      }
}

Its playing ads in muted state

**Comment by ypavlotsky** [comment] 2018-03-02 15:09
I'm closing this out as it appears to be working now. Feel free to comment and we'll re-open if the issue persists.

**Closed by ypavlotsky** 2018-03-02 15:09 UTC
Labels: IMA issue, P1
