### ISSUE TITLE
No ads showing

### ISSUE THREAD

**Issue by kakadanhem** [googleads/videojs-ima#240] opened 2016-06-25 15:11 UTC
I'm pretty new to this as I'm trying to set it up with video js. However I download the example and test it, no ads showing only my video playing. What am I missing here?

**Comment by shawnbuso** [comment] 2016-06-27 10:47
Hi there,

Do you have your own tag or are you using a sample tag? If you've got your own tag could you send it over? If you're using one of our sample tags it could be that your region doesn't have any ads trafficked - where are you located?

Thanks,
Shawn

**Comment by kakadanhem** [comment] 2016-06-29 03:51
Hi Shawn,

I use the sample tag I get from Google when I try to sign up for Adsense for video. I tried the sample code from Google (not working with videojs) it shows ads. My region is Cambodia (South East Asia). Maybe I could carefully try to set it up again and see if it shows?

Regards,
Kakada

**Comment by shawnbuso** [comment] 2016-06-30 09:39
Just to be clear, you're saying your tag works with a non-video.js player, but doesn't work with our video.js player, right? Does it work in our [VSI](https://developers.google.com/interactive-media-ads/docs/sdks/html5/vastinspector)? Could you share your tag so I can try it out on my end? Thanks!

**Comment by famthangbk** [comment] 2016-07-25 22:25
Hi #shawnbuso
please help me
my player not show ads when i used ads tag on iphone sample
`adTagUrl: 'http://googleads.g.doubleclick.net/pagead/ads?ad_type=video&client=ca-video-pub-4968145218643279&videoad_start_delay=0&description_url=http%3A%2F%2Fwww.google.com&max_ad_duration=40000&adtest=on'
`
i want use adsense for video
if i use simple or advance sample for my web, in ads.js file,although i have changed 'tab' to 'touchend', but can't play video when i touch
if i use iphone sample and sample ads tag every thing ok, but when i change ads

`http://googleads.g.doubleclick.net/pagead/ads?ad_type=video&client=ca-video-pub-4968145218643279&videoad_start_delay=0&description_url=http%3A%2F%2Fwww.google.com&max_ad_duration=40000&adtest=on`
no ads show on both desktop and moblie (android and ios)

**Comment by shawnbuso** [comment] 2016-07-26 14:47
Hi @famthangbk - it looks like you're trying to use TrueView ads, which are not supported on iPhone. I think they're also not working on desktop as a by-product of how we need to set up the iPhone sample to work with iPhones. The simple sample, however, is working for me with your tag when I change the event to 'touchend'. Are you seeing anything in the developer log for Safari that would indicate what the problem is?

**Comment by famthangbk** [comment] 2016-07-26 19:53
thank you for your enthusiastic support
lets me check again

**Comment by shawnbuso** [comment] 2016-08-29 15:22
Did that work for you? Let me know so I can close it out - thanks!

**Comment by shawnbuso** [comment] 2016-09-21 16:15
Closing for lack of response - if you're still seeing issues please feel free to re-open. Thanks!

**Closed by shawnbuso** 2016-09-21 16:15 UTC
Labels: support
