### ISSUE TITLE
 after calling player.dispose() videojs.ima crashes

### ISSUE THREAD

**Issue by damjan25** [googleads/videojs-ima#1117] opened 2023-08-17 14:48 UTC
After I try to fetch for ads I call player.dispose();  if none of the demand has ads
After that videojs.ima crahes and goes into infinite loop throwing these 2 errors: 

![image](https://github.com/googleads/videojs-ima/assets/60606529/b8f006a8-7375-4493-95bf-f583ca89b1dc)

First time I saw this bug was today. 

Browser: Chrome Desktop
"videojs-ima": "^2.2.0"
"@types/video.js": "^7.3.52",

**Comment by damjan25** [comment] 2023-08-18 09:07
it happens only on chrome v116!

It works on chrome (v115, v114), safari, edge, firefox.

before this happens I get this readyforpostroll warning in console (ONLY CHROME v116) and play() promise fails 4 times (player is muted)
![image](https://github.com/googleads/videojs-ima/assets/60606529/4e0ae30c-a1df-4442-902c-c2bc7729a264)

**Comment by dioramayuanito** [comment] 2023-08-18 09:26
i'm curious too about graceful dispose of video.js . how about adding these lines before player.dispose() ?

player.ads.reset();
player.ima.controller.sdkImpl.reset();
player.dispose();

**Comment by Kiro705** [comment] 2023-08-18 14:47
Hello @dioramayuanito ,

I was testing this, but could not reproduce the issue.

Testing with:
"video.js": "^8.3.0",
"videojs-ima": "2.2.0"
chrome: 116.0.5845.96

The test was done by calling player.dispose() during a preroll ad. No errors were encountered.

Would it be possible to share a code snippet or a video recording of the error. That may help me better reproduce the issue on my end.

Thank you,
Jackson
IMA SDK team

**Comment by damjan25** [comment] 2023-08-18 14:56
Thank you for your response guys. 

@dioramayuanito I tried putting player.ads.reset(); before calling .dispose() but unfortunately still the same issue. 
I wanted to try the other one as well but I can not find on what I should call sdkImpl.reset(); on :/ for me this function name is undefined


@Kiro705 thank you for checking. I will try to make test env to reproduce this. Basically we have 2 preroll ads and then content after it. And after 1st ad is done playing and then calling .dispose() then videojs-ima starts permanently throwing these 2 errors above :/

**Comment by MathkQ** [comment] 2023-11-14 12:31
Hi,  @Kiro705 @damjan25 @dioramayuanito 
I have the same issue.
In my case, the problem occurs because the method [PlayerWrapper.prototype.setUpPlayerIntervals](https://github.com/googleads/videojs-ima/blob/0a341373122e789843d56f3ea0c04d74d0380d0a/src/client-side/player-wrapper.js#L159) is set twice. Firstly when PlayerWrapper is [initialized](https://github.com/googleads/videojs-ima/blob/0a341373122e789843d56f3ea0c04d74d0380d0a/src/client-side/player-wrapper.js#L135C5-L135C5) and secondly when [PlayerWrapper.prototype.localContentEndedListener](https://github.com/googleads/videojs-ima/blob/0a341373122e789843d56f3ea0c04d74d0380d0a/src/client-side/player-wrapper.js#L232) is executed.

I think the best solution for that will be to move 

`clearInterval(this.updateTimeIntervalHandle);
  clearInterval(this.seekCheckIntervalHandle);
  clearInterval(this.resizeCheckIntervalHandle);`

straitly to the PlayerWrapper.prototype.setUpPlayerIntervals so from [here](https://github.com/googleads/videojs-ima/blob/0a341373122e789843d56f3ea0c04d74d0380d0a/src/client-side/player-wrapper.js#L228C1-L230C49) to the begin of the method [PlayerWrapper.prototype.setUpPlayerIntervals](https://github.com/googleads/videojs-ima/blob/0a341373122e789843d56f3ea0c04d74d0380d0a/src/client-side/player-wrapper.js#L159)

Summarize: the problem is when the plugin override interval handlers without cleaning olds one.

**Comment by MathkQ** [comment] 2023-11-20 15:33
@damjan25 for now you can solve this problem by executing this as a workaround:
`player.ima.controller.playerWrapper.playerDisposedListener();`
before:
`player.dispose();`

@Kiro705 can someone look at that PR?

**Comment by rtkac** [comment] 2023-11-22 15:17
Hello, same issue here.

Workaround doesn't work for me:
`player.ima.controller.playerWrapper.playerDisposedListener();`
before:
`player.dispose();`

But I can confirm, that the solution to move clearIntervals to [PlayerWrapper.prototype.setUpPlayerIntervals](https://github.com/googleads/videojs-ima/blob/0a341373122e789843d56f3ea0c04d74d0380d0a/src/client-side/player-wrapper.js#L159), mentioned by @MathkQ, worked as expected!

When we can please expect new version of videojs-ima?

Thanks a lot!

**Comment by Kiro705** [comment] 2024-01-04 16:35
Hi all,

The changes are merged in https://github.com/googleads/videojs-ima/commit/75ecf39973fae646602de84f3855541fadd01e40. They should make it into the next videoJS release.

**Closed by Kiro705** 2024-01-04 16:35 UTC
Labels: bug, P2
