### ISSUE TITLE
Ads skipped on iPad devices

### ISSUE THREAD

**Issue by amusakhan2016** [googleads/videojs-ima#1022] opened 2022-01-25 08:38 UTC
Hello, 

We are testing VideoJS player and seeing ads are skipped. Anyone is facing the same problem with VideoJS player?
screencast: https://drive.google.com/file/d/1N5OcPho5i1o4xCnjLO-jL2tgJtr5AkOh/view?usp=sharing

Thanks,

**Comment by Kiro705** [comment] 2022-02-02 21:10
Hello @amusakhan2016 ,

You may need to call [ImaSdkSettings.setDisableCustomPlaybackForIOS10Plus(true)](https://developers.google.com/interactive-media-ads/docs/sdks/html5/client-side/reference/js/google.ima.ImaSdkSettings#setDisableCustomPlaybackForIOS10Plus) to play certain ads on iPad and other iOS devices.

Do you have any steps to reproduce the skipped ads in any of the [videoJS-IMA samples](https://github.com/googleads/videojs-ima/tree/master/examples)?

Thank you,
Jackson
IMA SDK team

**Comment by amusakhan2016** [comment] 2022-02-03 05:44
Hello @Kiro705 
We tried this settings before let us try again. 

You can reproduce the issue with examples/simple, just use any vast tag (from Google example) and open the page in iPad. 

Thanks,

**Comment by Kiro705** [comment] 2022-02-03 19:07
Thank you @amusakhan2016 ,

I just now tested this, but saw ads successfully play.
Device: iPad Air, iOS: 12.5.5
Browser: Chrome v85.0.4183.109
Link: https://googleads.github.io/videojs-ima/examples/simple/

Let me know if this is different from what you are seeing, or if there are additional steps to reproduce.

**Comment by amusakhan2016** [comment] 2022-02-11 05:50
Hello Kiro, 

Thank you for the update, we checked the publisher and they using the following device/browser.
Model: iPad Air 2
iOS: 14.6 
Safari

Thanks,

**Comment by amusakhan2016** [comment] 2022-03-29 10:20
Hello Kiro, 

Any update on this issue or will you able to replicate the problem?

Thanks,

**Comment by Kiro705** [comment] 2022-03-30 20:01
Hello @amusakhan2016 ,

The IMA team currently does not have access to an iPad Air 2, but I will test this once we have access.

If you are able to reproduce on the device, is there any error message related to ads being skipped? Is it all adds ([IMA test ads](https://developers.google.com/interactive-media-ads/docs/sdks/html5/client-side/tags)) or only a certain VAST?

**Comment by Kiro705** [comment] 2022-05-05 20:42
Hello @amusakhan2016 

My team has still be unable to reproduce this issue, do you have any additional details that could help us with the issue? We do not have an available iPad Air 2 to test with.

**Comment by amusakhan2016** [comment] 2022-05-06 05:36
Hello @Kiro705 

I requested from the team to share debugging data but unfortunately there is no feedback from them yet. 

Thanks,

**Comment by Kiro705** [comment] 2022-06-14 15:38
Closing this issue, but feel free to reopen if it with additional steps to reproduce the issue.

**Closed by Kiro705** 2022-06-14 15:38 UTC
Labels: support, P2
