### ISSUE TITLE
Playlist example bugs

### ISSUE THREAD

**Issue by yshterev** [googleads/videojs-ima#343] opened 2017-03-24 16:52 UTC
Live demo [here](https://yshterev.github.io/videojs-ima/examples/playlist/)

Issue 1
---
If Single Non-linear Inline (Banner) ad is loaded after linear ad was loaded before, banner do not show.

**Steps to reproduce** 
Start Video 3, skip the ad and then start Video 4. 

**Result** 
Banner is hidden. If you refresh and start Video 4 directly banner is working. 

I think the problem is [here](https://github.com/googleads/videojs-ima/blob/master/src/videojs.ima.js#L423)

Issue 2
---
If the ad has a mid-roll, and after mid-roll ends you change to another video with ad that also has mid-roll, the second video ad starts directly at mid-roll and then plays pre-roll.

**Steps to reproduce:** 
Start Video 1, wait mid-roll end, then change to Video 2. 

**Result** 
Video 2 ad will start from mid-roll and then play pre-roll.

Questions
---

1. Why changing videos while running ad is prevented in the demo?
2. Is the plugin supposed unload and load new ads properly if source and tag change is made while ad is playing?

 I have to some issues with this, but I am not yet sure if its my code or the plugin.

**Comment by yshterev** [comment] 2017-04-03 08:31
@shawnbuso any feedback please?

**Comment by shawnbuso** [comment] 2017-04-05 19:40
Sorry for the delay - I think I have a fix for issue 1 - we were hiding the ad display container on resetIMA, and we shouldn't have been doing that. That should be fixed with PR #350.

Re: issue 2, it looks like this could be an IMA SDK issue. I'm looking into it with the rest of the team and I'll let you know what we find. Thanks!

**Comment by yshterev** [comment] 2017-04-06 07:43
Tested the fix for issue 1 on my fork. Seems good :)

**Comment by shawnbuso** [comment] 2017-06-08 19:41
The second issue here was fixed by #374 (it says it fixes the second issue in #354 but that's a dupe of the second issue here), so we should be good to go :)

**Closed by shawnbuso** 2017-06-08 19:41 UTC
Labels: bug, IMA issue
