### ISSUE TITLE
Stop playing AD video after clicking to the AD area.

### ISSUE THREAD

**Issue by OlegT-R** [googleads/videojs-ima#776] opened 2019-01-22 12:43 UTC
Hi all.
After I clicked to the ad area, it redirect to the another page. The video does not stop, but the button is ima-paused.
This behavior can be seen in the example [https://googleads.github.io/videojs-ima/examples/simple/](url)
Its ad click event 
`this.adsManager.addEventListener(google.ima.AdEvent.Type.CLICK, this.onAdPaused.bind(this)); `
`SdkImpl.prototype.onAdPaused = function () {
  this.controller.onAdsPaused();
};`
This method does not stop ad playing. If i put this.pauseAds() to this method ad is working correctly

**Comment by rudyzeinoun** [comment] 2019-08-22 14:34
I can confirm I have the same problem.

I fixed it by changing line 450 in `src/sdk-impl.js`
`SdkImpl.prototype.onAdPaused = function () {`
`  this.controller.onAdsPaused();`
`};`


into:
`SdkImpl.prototype.onAdPaused = function () {`
`  this.controller.pauseAd();`
`};`

Is it just us or should this be committed back to the source?

**Comment by arnaudcasame** [comment] 2019-08-22 21:05
Hi,

I was able to reproduce the behavior that you're seeing with the current ad not pausing when you click through it. I'll share the behavior with the rest of the team and I'll come back to you once we have our findings.

**Comment by arnaudcasame** [comment] 2019-10-10 21:02
Hi,

I’m closing this issue because it has been solved with the [v1.7.0](https://github.com/googleads/videojs-ima/releases/tag/v1.7.0) release. 

Please reopen if you still encounter this issue.

Thank you!

**Closed by arnaudcasame** 2019-10-10 21:02 UTC
Labels: blocked

**Comment by rudyzeinoun** [comment] 2019-10-17 11:39
It's not fixed on desktop browsers. The same issue is still happening, and I don't see any commits related to fixing it. Can you point out the relevant commit to debug this more from my end?

**Comment by sndpl** [comment] 2019-11-18 18:37
@arnaudcasame We also still have the same issue, can you reopen this ticket or point the relevant commit where this has been fixed?

**Comment by arnaudcasame** [comment] 2019-11-19 19:13
Hi,
The behavior was fixed on this [commit](https://github.com/googleads/videojs-ima/commit/0b63fb12207bc76d08b570916e84202c5a55136f)

**Comment by Kiro705** [comment] 2019-11-19 19:34
Hi all,

Sorry for the confusion regarding this issue. The expected behavior for the IMA SDK is on ad click-through, the ad does continue playing. The above commit made this so the play/pause button does not switch to pause on click-through.

If you would like your own player to pause on click-through, that behavior is dependent on your own implementation.
